/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.uhh.l2g.plugins.migration.model.LegacyLicense;
import de.uhh.l2g.plugins.migration.model.LegacyLicenseModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LegacyLicense service. Represents a row in the &quot;license&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.migration.model.LegacyLicenseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LegacyLicenseImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyLicenseImpl
 * @see de.uhh.l2g.plugins.migration.model.LegacyLicense
 * @see de.uhh.l2g.plugins.migration.model.LegacyLicenseModel
 * @generated
 */
public class LegacyLicenseModelImpl extends BaseModelImpl<LegacyLicense>
	implements LegacyLicenseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a legacy license model instance should use the {@link de.uhh.l2g.plugins.migration.model.LegacyLicense} interface instead.
	 */
	public static final String TABLE_NAME = "license";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "videoId", Types.BIGINT },
			{ "ccby", Types.INTEGER },
			{ "ccbybc", Types.INTEGER },
			{ "ccbyncnd", Types.INTEGER },
			{ "ccbyncsa", Types.INTEGER },
			{ "ccbysa", Types.INTEGER },
			{ "ccbync", Types.INTEGER },
			{ "l2go", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table license (id_ LONG not null primary key,videoId LONG,ccby INTEGER,ccbybc INTEGER,ccbyncnd INTEGER,ccbyncsa INTEGER,ccbysa INTEGER,ccbync INTEGER,l2go INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table license";
	public static final String ORDER_BY_JPQL = " ORDER BY legacyLicense.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY license.id_ ASC";
	public static final String DATA_SOURCE = "anotherDataSource";
	public static final String SESSION_FACTORY = "anotherSessionFactory";
	public static final String TX_MANAGER = "anotherTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.migration.model.LegacyLicense"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.migration.model.LegacyLicense"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.migration.model.LegacyLicense"));

	public LegacyLicenseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LegacyLicense.class;
	}

	@Override
	public String getModelClassName() {
		return LegacyLicense.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("videoId", getVideoId());
		attributes.put("ccby", getCcby());
		attributes.put("ccbybc", getCcbybc());
		attributes.put("ccbyncnd", getCcbyncnd());
		attributes.put("ccbyncsa", getCcbyncsa());
		attributes.put("ccbysa", getCcbysa());
		attributes.put("ccbync", getCcbync());
		attributes.put("l2go", getL2go());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long videoId = (Long)attributes.get("videoId");

		if (videoId != null) {
			setVideoId(videoId);
		}

		Integer ccby = (Integer)attributes.get("ccby");

		if (ccby != null) {
			setCcby(ccby);
		}

		Integer ccbybc = (Integer)attributes.get("ccbybc");

		if (ccbybc != null) {
			setCcbybc(ccbybc);
		}

		Integer ccbyncnd = (Integer)attributes.get("ccbyncnd");

		if (ccbyncnd != null) {
			setCcbyncnd(ccbyncnd);
		}

		Integer ccbyncsa = (Integer)attributes.get("ccbyncsa");

		if (ccbyncsa != null) {
			setCcbyncsa(ccbyncsa);
		}

		Integer ccbysa = (Integer)attributes.get("ccbysa");

		if (ccbysa != null) {
			setCcbysa(ccbysa);
		}

		Integer ccbync = (Integer)attributes.get("ccbync");

		if (ccbync != null) {
			setCcbync(ccbync);
		}

		Integer l2go = (Integer)attributes.get("l2go");

		if (l2go != null) {
			setL2go(l2go);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_videoId = videoId;
	}

	@Override
	public int getCcby() {
		return _ccby;
	}

	@Override
	public void setCcby(int ccby) {
		_ccby = ccby;
	}

	@Override
	public int getCcbybc() {
		return _ccbybc;
	}

	@Override
	public void setCcbybc(int ccbybc) {
		_ccbybc = ccbybc;
	}

	@Override
	public int getCcbyncnd() {
		return _ccbyncnd;
	}

	@Override
	public void setCcbyncnd(int ccbyncnd) {
		_ccbyncnd = ccbyncnd;
	}

	@Override
	public int getCcbyncsa() {
		return _ccbyncsa;
	}

	@Override
	public void setCcbyncsa(int ccbyncsa) {
		_ccbyncsa = ccbyncsa;
	}

	@Override
	public int getCcbysa() {
		return _ccbysa;
	}

	@Override
	public void setCcbysa(int ccbysa) {
		_ccbysa = ccbysa;
	}

	@Override
	public int getCcbync() {
		return _ccbync;
	}

	@Override
	public void setCcbync(int ccbync) {
		_ccbync = ccbync;
	}

	@Override
	public int getL2go() {
		return _l2go;
	}

	@Override
	public void setL2go(int l2go) {
		_l2go = l2go;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LegacyLicense.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LegacyLicense toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LegacyLicense)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LegacyLicenseImpl legacyLicenseImpl = new LegacyLicenseImpl();

		legacyLicenseImpl.setId(getId());
		legacyLicenseImpl.setVideoId(getVideoId());
		legacyLicenseImpl.setCcby(getCcby());
		legacyLicenseImpl.setCcbybc(getCcbybc());
		legacyLicenseImpl.setCcbyncnd(getCcbyncnd());
		legacyLicenseImpl.setCcbyncsa(getCcbyncsa());
		legacyLicenseImpl.setCcbysa(getCcbysa());
		legacyLicenseImpl.setCcbync(getCcbync());
		legacyLicenseImpl.setL2go(getL2go());

		legacyLicenseImpl.resetOriginalValues();

		return legacyLicenseImpl;
	}

	@Override
	public int compareTo(LegacyLicense legacyLicense) {
		long primaryKey = legacyLicense.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LegacyLicense)) {
			return false;
		}

		LegacyLicense legacyLicense = (LegacyLicense)obj;

		long primaryKey = legacyLicense.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<LegacyLicense> toCacheModel() {
		LegacyLicenseCacheModel legacyLicenseCacheModel = new LegacyLicenseCacheModel();

		legacyLicenseCacheModel.id = getId();

		legacyLicenseCacheModel.videoId = getVideoId();

		legacyLicenseCacheModel.ccby = getCcby();

		legacyLicenseCacheModel.ccbybc = getCcbybc();

		legacyLicenseCacheModel.ccbyncnd = getCcbyncnd();

		legacyLicenseCacheModel.ccbyncsa = getCcbyncsa();

		legacyLicenseCacheModel.ccbysa = getCcbysa();

		legacyLicenseCacheModel.ccbync = getCcbync();

		legacyLicenseCacheModel.l2go = getL2go();

		return legacyLicenseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", videoId=");
		sb.append(getVideoId());
		sb.append(", ccby=");
		sb.append(getCcby());
		sb.append(", ccbybc=");
		sb.append(getCcbybc());
		sb.append(", ccbyncnd=");
		sb.append(getCcbyncnd());
		sb.append(", ccbyncsa=");
		sb.append(getCcbyncsa());
		sb.append(", ccbysa=");
		sb.append(getCcbysa());
		sb.append(", ccbync=");
		sb.append(getCcbync());
		sb.append(", l2go=");
		sb.append(getL2go());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.migration.model.LegacyLicense");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoId</column-name><column-value><![CDATA[");
		sb.append(getVideoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccby</column-name><column-value><![CDATA[");
		sb.append(getCcby());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbybc</column-name><column-value><![CDATA[");
		sb.append(getCcbybc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbyncnd</column-name><column-value><![CDATA[");
		sb.append(getCcbyncnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbyncsa</column-name><column-value><![CDATA[");
		sb.append(getCcbyncsa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbysa</column-name><column-value><![CDATA[");
		sb.append(getCcbysa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbync</column-name><column-value><![CDATA[");
		sb.append(getCcbync());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>l2go</column-name><column-value><![CDATA[");
		sb.append(getL2go());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LegacyLicense.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LegacyLicense.class
		};
	private long _id;
	private long _videoId;
	private int _ccby;
	private int _ccbybc;
	private int _ccbyncnd;
	private int _ccbyncsa;
	private int _ccbysa;
	private int _ccbync;
	private int _l2go;
	private LegacyLicense _escapedModel;
}