/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import de.uhh.l2g.plugins.migration.model.LegacyStatistic;
import de.uhh.l2g.plugins.migration.model.LegacyStatisticModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LegacyStatistic service. Represents a row in the &quot;videostats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.migration.model.LegacyStatisticModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LegacyStatisticImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyStatisticImpl
 * @see de.uhh.l2g.plugins.migration.model.LegacyStatistic
 * @see de.uhh.l2g.plugins.migration.model.LegacyStatisticModel
 * @generated
 */
public class LegacyStatisticModelImpl extends BaseModelImpl<LegacyStatistic>
	implements LegacyStatisticModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a legacy statistic model instance should use the {@link de.uhh.l2g.plugins.migration.model.LegacyStatistic} interface instead.
	 */
	public static final String TABLE_NAME = "videostats";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.INTEGER },
			{ "public_", Types.INTEGER },
			{ "private_", Types.INTEGER },
			{ "autofill", Types.INTEGER },
			{ "date_", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table videostats (id_ INTEGER not null primary key,public_ INTEGER,private_ INTEGER,autofill INTEGER,date_ DATE null)";
	public static final String TABLE_SQL_DROP = "drop table videostats";
	public static final String ORDER_BY_JPQL = " ORDER BY legacyStatistic.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY videostats.id_ ASC";
	public static final String DATA_SOURCE = "anotherDataSource";
	public static final String SESSION_FACTORY = "anotherSessionFactory";
	public static final String TX_MANAGER = "anotherTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.migration.model.LegacyStatistic"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.migration.model.LegacyStatistic"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.migration.model.LegacyStatistic"));

	public LegacyStatisticModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LegacyStatistic.class;
	}

	@Override
	public String getModelClassName() {
		return LegacyStatistic.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("public_", getPublic_());
		attributes.put("private_", getPrivate_());
		attributes.put("autofill", getAutofill());
		attributes.put("date_", getDate_());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer public_ = (Integer)attributes.get("public_");

		if (public_ != null) {
			setPublic_(public_);
		}

		Integer private_ = (Integer)attributes.get("private_");

		if (private_ != null) {
			setPrivate_(private_);
		}

		Integer autofill = (Integer)attributes.get("autofill");

		if (autofill != null) {
			setAutofill(autofill);
		}

		Date date_ = (Date)attributes.get("date_");

		if (date_ != null) {
			setDate_(date_);
		}
	}

	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_id = id;
	}

	@Override
	public int getPublic_() {
		return _public_;
	}

	@Override
	public void setPublic_(int public_) {
		_public_ = public_;
	}

	@Override
	public int getPrivate_() {
		return _private_;
	}

	@Override
	public void setPrivate_(int private_) {
		_private_ = private_;
	}

	@Override
	public int getAutofill() {
		return _autofill;
	}

	@Override
	public void setAutofill(int autofill) {
		_autofill = autofill;
	}

	@Override
	public Date getDate_() {
		return _date_;
	}

	@Override
	public void setDate_(Date date_) {
		_date_ = date_;
	}

	@Override
	public LegacyStatistic toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LegacyStatistic)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LegacyStatisticImpl legacyStatisticImpl = new LegacyStatisticImpl();

		legacyStatisticImpl.setId(getId());
		legacyStatisticImpl.setPublic_(getPublic_());
		legacyStatisticImpl.setPrivate_(getPrivate_());
		legacyStatisticImpl.setAutofill(getAutofill());
		legacyStatisticImpl.setDate_(getDate_());

		legacyStatisticImpl.resetOriginalValues();

		return legacyStatisticImpl;
	}

	@Override
	public int compareTo(LegacyStatistic legacyStatistic) {
		int primaryKey = legacyStatistic.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LegacyStatistic)) {
			return false;
		}

		LegacyStatistic legacyStatistic = (LegacyStatistic)obj;

		int primaryKey = legacyStatistic.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<LegacyStatistic> toCacheModel() {
		LegacyStatisticCacheModel legacyStatisticCacheModel = new LegacyStatisticCacheModel();

		legacyStatisticCacheModel.id = getId();

		legacyStatisticCacheModel.public_ = getPublic_();

		legacyStatisticCacheModel.private_ = getPrivate_();

		legacyStatisticCacheModel.autofill = getAutofill();

		Date date_ = getDate_();

		if (date_ != null) {
			legacyStatisticCacheModel.date_ = date_.getTime();
		}
		else {
			legacyStatisticCacheModel.date_ = Long.MIN_VALUE;
		}

		return legacyStatisticCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", public_=");
		sb.append(getPublic_());
		sb.append(", private_=");
		sb.append(getPrivate_());
		sb.append(", autofill=");
		sb.append(getAutofill());
		sb.append(", date_=");
		sb.append(getDate_());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.migration.model.LegacyStatistic");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>public_</column-name><column-value><![CDATA[");
		sb.append(getPublic_());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>private_</column-name><column-value><![CDATA[");
		sb.append(getPrivate_());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>autofill</column-name><column-value><![CDATA[");
		sb.append(getAutofill());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date_</column-name><column-value><![CDATA[");
		sb.append(getDate_());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LegacyStatistic.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LegacyStatistic.class
		};
	private int _id;
	private int _public_;
	private int _private_;
	private int _autofill;
	private Date _date_;
	private LegacyStatistic _escapedModel;
}