/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.uhh.l2g.plugins.model.Coordinator;
import de.uhh.l2g.plugins.model.CoordinatorModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Coordinator service. Represents a row in the &quot;LG_Coordinator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.model.CoordinatorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CoordinatorImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see CoordinatorImpl
 * @see de.uhh.l2g.plugins.model.Coordinator
 * @see de.uhh.l2g.plugins.model.CoordinatorModel
 * @generated
 */
public class CoordinatorModelImpl extends BaseModelImpl<Coordinator>
	implements CoordinatorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a coordinator model instance should use the {@link de.uhh.l2g.plugins.model.Coordinator} interface instead.
	 */
	public static final String TABLE_NAME = "LG_Coordinator";
	public static final Object[][] TABLE_COLUMNS = {
			{ "coordinatorId", Types.BIGINT },
			{ "institutionId", Types.BIGINT },
			{ "officeId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table LG_Coordinator (coordinatorId LONG not null primary key,institutionId LONG,officeId LONG)";
	public static final String TABLE_SQL_DROP = "drop table LG_Coordinator";
	public static final String ORDER_BY_JPQL = " ORDER BY coordinator.coordinatorId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LG_Coordinator.coordinatorId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Coordinator"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Coordinator"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Coordinator"),
			true);
	public static long INSTITUTIONID_COLUMN_BITMASK = 1L;
	public static long OFFICEID_COLUMN_BITMASK = 2L;
	public static long COORDINATORID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.model.Coordinator"));

	public CoordinatorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _coordinatorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCoordinatorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _coordinatorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Coordinator.class;
	}

	@Override
	public String getModelClassName() {
		return Coordinator.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("coordinatorId", getCoordinatorId());
		attributes.put("institutionId", getInstitutionId());
		attributes.put("officeId", getOfficeId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long coordinatorId = (Long)attributes.get("coordinatorId");

		if (coordinatorId != null) {
			setCoordinatorId(coordinatorId);
		}

		Long institutionId = (Long)attributes.get("institutionId");

		if (institutionId != null) {
			setInstitutionId(institutionId);
		}

		Long officeId = (Long)attributes.get("officeId");

		if (officeId != null) {
			setOfficeId(officeId);
		}
	}

	@Override
	public long getCoordinatorId() {
		return _coordinatorId;
	}

	@Override
	public void setCoordinatorId(long coordinatorId) {
		_coordinatorId = coordinatorId;
	}

	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@Override
	public long getOfficeId() {
		return _officeId;
	}

	@Override
	public void setOfficeId(long officeId) {
		_columnBitmask |= OFFICEID_COLUMN_BITMASK;

		if (!_setOriginalOfficeId) {
			_setOriginalOfficeId = true;

			_originalOfficeId = _officeId;
		}

		_officeId = officeId;
	}

	public long getOriginalOfficeId() {
		return _originalOfficeId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Coordinator.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Coordinator toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Coordinator)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CoordinatorImpl coordinatorImpl = new CoordinatorImpl();

		coordinatorImpl.setCoordinatorId(getCoordinatorId());
		coordinatorImpl.setInstitutionId(getInstitutionId());
		coordinatorImpl.setOfficeId(getOfficeId());

		coordinatorImpl.resetOriginalValues();

		return coordinatorImpl;
	}

	@Override
	public int compareTo(Coordinator coordinator) {
		long primaryKey = coordinator.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Coordinator)) {
			return false;
		}

		Coordinator coordinator = (Coordinator)obj;

		long primaryKey = coordinator.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CoordinatorModelImpl coordinatorModelImpl = this;

		coordinatorModelImpl._originalInstitutionId = coordinatorModelImpl._institutionId;

		coordinatorModelImpl._setOriginalInstitutionId = false;

		coordinatorModelImpl._originalOfficeId = coordinatorModelImpl._officeId;

		coordinatorModelImpl._setOriginalOfficeId = false;

		coordinatorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Coordinator> toCacheModel() {
		CoordinatorCacheModel coordinatorCacheModel = new CoordinatorCacheModel();

		coordinatorCacheModel.coordinatorId = getCoordinatorId();

		coordinatorCacheModel.institutionId = getInstitutionId();

		coordinatorCacheModel.officeId = getOfficeId();

		return coordinatorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{coordinatorId=");
		sb.append(getCoordinatorId());
		sb.append(", institutionId=");
		sb.append(getInstitutionId());
		sb.append(", officeId=");
		sb.append(getOfficeId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.model.Coordinator");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>coordinatorId</column-name><column-value><![CDATA[");
		sb.append(getCoordinatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>institutionId</column-name><column-value><![CDATA[");
		sb.append(getInstitutionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>officeId</column-name><column-value><![CDATA[");
		sb.append(getOfficeId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Coordinator.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Coordinator.class
		};
	private long _coordinatorId;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _officeId;
	private long _originalOfficeId;
	private boolean _setOriginalOfficeId;
	private long _columnBitmask;
	private Coordinator _escapedModel;
}