/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.uhh.l2g.plugins.model.Facility_Host;
import de.uhh.l2g.plugins.model.Facility_HostModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Facility_Host service. Represents a row in the &quot;LG_Facility_Host&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.model.Facility_HostModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Facility_HostImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Facility_HostImpl
 * @see de.uhh.l2g.plugins.model.Facility_Host
 * @see de.uhh.l2g.plugins.model.Facility_HostModel
 * @generated
 */
public class Facility_HostModelImpl extends BaseModelImpl<Facility_Host>
	implements Facility_HostModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a facility_ host model instance should use the {@link de.uhh.l2g.plugins.model.Facility_Host} interface instead.
	 */
	public static final String TABLE_NAME = "LG_Facility_Host";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fasilityHostId", Types.BIGINT },
			{ "facilityId", Types.BIGINT },
			{ "hostId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table LG_Facility_Host (fasilityHostId LONG not null primary key,facilityId LONG,hostId LONG)";
	public static final String TABLE_SQL_DROP = "drop table LG_Facility_Host";
	public static final String ORDER_BY_JPQL = " ORDER BY facility_Host.fasilityHostId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LG_Facility_Host.fasilityHostId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Facility_Host"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Facility_Host"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.model.Facility_Host"));

	public Facility_HostModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fasilityHostId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFasilityHostId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fasilityHostId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Facility_Host.class;
	}

	@Override
	public String getModelClassName() {
		return Facility_Host.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fasilityHostId", getFasilityHostId());
		attributes.put("facilityId", getFacilityId());
		attributes.put("hostId", getHostId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fasilityHostId = (Long)attributes.get("fasilityHostId");

		if (fasilityHostId != null) {
			setFasilityHostId(fasilityHostId);
		}

		Long facilityId = (Long)attributes.get("facilityId");

		if (facilityId != null) {
			setFacilityId(facilityId);
		}

		Long hostId = (Long)attributes.get("hostId");

		if (hostId != null) {
			setHostId(hostId);
		}
	}

	@Override
	public long getFasilityHostId() {
		return _fasilityHostId;
	}

	@Override
	public void setFasilityHostId(long fasilityHostId) {
		_fasilityHostId = fasilityHostId;
	}

	@Override
	public long getFacilityId() {
		return _facilityId;
	}

	@Override
	public void setFacilityId(long facilityId) {
		_facilityId = facilityId;
	}

	@Override
	public long getHostId() {
		return _hostId;
	}

	@Override
	public void setHostId(long hostId) {
		_hostId = hostId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Facility_Host.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Facility_Host toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Facility_Host)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Facility_HostImpl facility_HostImpl = new Facility_HostImpl();

		facility_HostImpl.setFasilityHostId(getFasilityHostId());
		facility_HostImpl.setFacilityId(getFacilityId());
		facility_HostImpl.setHostId(getHostId());

		facility_HostImpl.resetOriginalValues();

		return facility_HostImpl;
	}

	@Override
	public int compareTo(Facility_Host facility_Host) {
		long primaryKey = facility_Host.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Facility_Host)) {
			return false;
		}

		Facility_Host facility_Host = (Facility_Host)obj;

		long primaryKey = facility_Host.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Facility_Host> toCacheModel() {
		Facility_HostCacheModel facility_HostCacheModel = new Facility_HostCacheModel();

		facility_HostCacheModel.fasilityHostId = getFasilityHostId();

		facility_HostCacheModel.facilityId = getFacilityId();

		facility_HostCacheModel.hostId = getHostId();

		return facility_HostCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{fasilityHostId=");
		sb.append(getFasilityHostId());
		sb.append(", facilityId=");
		sb.append(getFacilityId());
		sb.append(", hostId=");
		sb.append(getHostId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.model.Facility_Host");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fasilityHostId</column-name><column-value><![CDATA[");
		sb.append(getFasilityHostId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facilityId</column-name><column-value><![CDATA[");
		sb.append(getFacilityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hostId</column-name><column-value><![CDATA[");
		sb.append(getHostId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Facility_Host.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Facility_Host.class
		};
	private long _fasilityHostId;
	private long _facilityId;
	private long _hostId;
	private Facility_Host _escapedModel;
}