/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.uhh.l2g.plugins.model.Lectureseries_Creator;
import de.uhh.l2g.plugins.model.Lectureseries_CreatorModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Lectureseries_Creator service. Represents a row in the &quot;LG_Lectureseries_Creator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.model.Lectureseries_CreatorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Lectureseries_CreatorImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Lectureseries_CreatorImpl
 * @see de.uhh.l2g.plugins.model.Lectureseries_Creator
 * @see de.uhh.l2g.plugins.model.Lectureseries_CreatorModel
 * @generated
 */
public class Lectureseries_CreatorModelImpl extends BaseModelImpl<Lectureseries_Creator>
	implements Lectureseries_CreatorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lectureseries_ creator model instance should use the {@link de.uhh.l2g.plugins.model.Lectureseries_Creator} interface instead.
	 */
	public static final String TABLE_NAME = "LG_Lectureseries_Creator";
	public static final Object[][] TABLE_COLUMNS = {
			{ "lectureseriesCreatorId", Types.BIGINT },
			{ "lectureseriesId", Types.BIGINT },
			{ "creatorId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table LG_Lectureseries_Creator (lectureseriesCreatorId LONG not null primary key,lectureseriesId LONG,creatorId LONG)";
	public static final String TABLE_SQL_DROP = "drop table LG_Lectureseries_Creator";
	public static final String ORDER_BY_JPQL = " ORDER BY lectureseries_Creator.lectureseriesCreatorId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LG_Lectureseries_Creator.lectureseriesCreatorId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Lectureseries_Creator"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Lectureseries_Creator"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Lectureseries_Creator"),
			true);
	public static long CREATORID_COLUMN_BITMASK = 1L;
	public static long LECTURESERIESID_COLUMN_BITMASK = 2L;
	public static long LECTURESERIESCREATORID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.model.Lectureseries_Creator"));

	public Lectureseries_CreatorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lectureseriesCreatorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLectureseriesCreatorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lectureseriesCreatorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Lectureseries_Creator.class;
	}

	@Override
	public String getModelClassName() {
		return Lectureseries_Creator.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("lectureseriesCreatorId", getLectureseriesCreatorId());
		attributes.put("lectureseriesId", getLectureseriesId());
		attributes.put("creatorId", getCreatorId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long lectureseriesCreatorId = (Long)attributes.get(
				"lectureseriesCreatorId");

		if (lectureseriesCreatorId != null) {
			setLectureseriesCreatorId(lectureseriesCreatorId);
		}

		Long lectureseriesId = (Long)attributes.get("lectureseriesId");

		if (lectureseriesId != null) {
			setLectureseriesId(lectureseriesId);
		}

		Long creatorId = (Long)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}
	}

	@Override
	public long getLectureseriesCreatorId() {
		return _lectureseriesCreatorId;
	}

	@Override
	public void setLectureseriesCreatorId(long lectureseriesCreatorId) {
		_lectureseriesCreatorId = lectureseriesCreatorId;
	}

	@Override
	public long getLectureseriesId() {
		return _lectureseriesId;
	}

	@Override
	public void setLectureseriesId(long lectureseriesId) {
		_columnBitmask |= LECTURESERIESID_COLUMN_BITMASK;

		if (!_setOriginalLectureseriesId) {
			_setOriginalLectureseriesId = true;

			_originalLectureseriesId = _lectureseriesId;
		}

		_lectureseriesId = lectureseriesId;
	}

	public long getOriginalLectureseriesId() {
		return _originalLectureseriesId;
	}

	@Override
	public long getCreatorId() {
		return _creatorId;
	}

	@Override
	public void setCreatorId(long creatorId) {
		_columnBitmask |= CREATORID_COLUMN_BITMASK;

		if (!_setOriginalCreatorId) {
			_setOriginalCreatorId = true;

			_originalCreatorId = _creatorId;
		}

		_creatorId = creatorId;
	}

	public long getOriginalCreatorId() {
		return _originalCreatorId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Lectureseries_Creator.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Lectureseries_Creator toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Lectureseries_Creator)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Lectureseries_CreatorImpl lectureseries_CreatorImpl = new Lectureseries_CreatorImpl();

		lectureseries_CreatorImpl.setLectureseriesCreatorId(getLectureseriesCreatorId());
		lectureseries_CreatorImpl.setLectureseriesId(getLectureseriesId());
		lectureseries_CreatorImpl.setCreatorId(getCreatorId());

		lectureseries_CreatorImpl.resetOriginalValues();

		return lectureseries_CreatorImpl;
	}

	@Override
	public int compareTo(Lectureseries_Creator lectureseries_Creator) {
		long primaryKey = lectureseries_Creator.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Lectureseries_Creator)) {
			return false;
		}

		Lectureseries_Creator lectureseries_Creator = (Lectureseries_Creator)obj;

		long primaryKey = lectureseries_Creator.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		Lectureseries_CreatorModelImpl lectureseries_CreatorModelImpl = this;

		lectureseries_CreatorModelImpl._originalLectureseriesId = lectureseries_CreatorModelImpl._lectureseriesId;

		lectureseries_CreatorModelImpl._setOriginalLectureseriesId = false;

		lectureseries_CreatorModelImpl._originalCreatorId = lectureseries_CreatorModelImpl._creatorId;

		lectureseries_CreatorModelImpl._setOriginalCreatorId = false;

		lectureseries_CreatorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Lectureseries_Creator> toCacheModel() {
		Lectureseries_CreatorCacheModel lectureseries_CreatorCacheModel = new Lectureseries_CreatorCacheModel();

		lectureseries_CreatorCacheModel.lectureseriesCreatorId = getLectureseriesCreatorId();

		lectureseries_CreatorCacheModel.lectureseriesId = getLectureseriesId();

		lectureseries_CreatorCacheModel.creatorId = getCreatorId();

		return lectureseries_CreatorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{lectureseriesCreatorId=");
		sb.append(getLectureseriesCreatorId());
		sb.append(", lectureseriesId=");
		sb.append(getLectureseriesId());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.model.Lectureseries_Creator");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>lectureseriesCreatorId</column-name><column-value><![CDATA[");
		sb.append(getLectureseriesCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lectureseriesId</column-name><column-value><![CDATA[");
		sb.append(getLectureseriesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Lectureseries_Creator.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Lectureseries_Creator.class
		};
	private long _lectureseriesCreatorId;
	private long _lectureseriesId;
	private long _originalLectureseriesId;
	private boolean _setOriginalLectureseriesId;
	private long _creatorId;
	private long _originalCreatorId;
	private boolean _setOriginalCreatorId;
	private long _columnBitmask;
	private Lectureseries_Creator _escapedModel;
}