/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.uhh.l2g.plugins.model.Lectureseries_Facility;
import de.uhh.l2g.plugins.model.Lectureseries_FacilityModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Lectureseries_Facility service. Represents a row in the &quot;LG_Lectureseries_Facility&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.model.Lectureseries_FacilityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Lectureseries_FacilityImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Lectureseries_FacilityImpl
 * @see de.uhh.l2g.plugins.model.Lectureseries_Facility
 * @see de.uhh.l2g.plugins.model.Lectureseries_FacilityModel
 * @generated
 */
public class Lectureseries_FacilityModelImpl extends BaseModelImpl<Lectureseries_Facility>
	implements Lectureseries_FacilityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lectureseries_ facility model instance should use the {@link de.uhh.l2g.plugins.model.Lectureseries_Facility} interface instead.
	 */
	public static final String TABLE_NAME = "LG_Lectureseries_Facility";
	public static final Object[][] TABLE_COLUMNS = {
			{ "lectureseriesFacilityId", Types.BIGINT },
			{ "lectureseriesId", Types.BIGINT },
			{ "facilityId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table LG_Lectureseries_Facility (lectureseriesFacilityId LONG not null primary key,lectureseriesId LONG,facilityId LONG)";
	public static final String TABLE_SQL_DROP = "drop table LG_Lectureseries_Facility";
	public static final String ORDER_BY_JPQL = " ORDER BY lectureseries_Facility.lectureseriesFacilityId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LG_Lectureseries_Facility.lectureseriesFacilityId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Lectureseries_Facility"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Lectureseries_Facility"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.model.Lectureseries_Facility"));

	public Lectureseries_FacilityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _lectureseriesFacilityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLectureseriesFacilityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lectureseriesFacilityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Lectureseries_Facility.class;
	}

	@Override
	public String getModelClassName() {
		return Lectureseries_Facility.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("lectureseriesFacilityId", getLectureseriesFacilityId());
		attributes.put("lectureseriesId", getLectureseriesId());
		attributes.put("facilityId", getFacilityId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long lectureseriesFacilityId = (Long)attributes.get(
				"lectureseriesFacilityId");

		if (lectureseriesFacilityId != null) {
			setLectureseriesFacilityId(lectureseriesFacilityId);
		}

		Long lectureseriesId = (Long)attributes.get("lectureseriesId");

		if (lectureseriesId != null) {
			setLectureseriesId(lectureseriesId);
		}

		Long facilityId = (Long)attributes.get("facilityId");

		if (facilityId != null) {
			setFacilityId(facilityId);
		}
	}

	@Override
	public long getLectureseriesFacilityId() {
		return _lectureseriesFacilityId;
	}

	@Override
	public void setLectureseriesFacilityId(long lectureseriesFacilityId) {
		_lectureseriesFacilityId = lectureseriesFacilityId;
	}

	@Override
	public long getLectureseriesId() {
		return _lectureseriesId;
	}

	@Override
	public void setLectureseriesId(long lectureseriesId) {
		_lectureseriesId = lectureseriesId;
	}

	@Override
	public long getFacilityId() {
		return _facilityId;
	}

	@Override
	public void setFacilityId(long facilityId) {
		_facilityId = facilityId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Lectureseries_Facility.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Lectureseries_Facility toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Lectureseries_Facility)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Lectureseries_FacilityImpl lectureseries_FacilityImpl = new Lectureseries_FacilityImpl();

		lectureseries_FacilityImpl.setLectureseriesFacilityId(getLectureseriesFacilityId());
		lectureseries_FacilityImpl.setLectureseriesId(getLectureseriesId());
		lectureseries_FacilityImpl.setFacilityId(getFacilityId());

		lectureseries_FacilityImpl.resetOriginalValues();

		return lectureseries_FacilityImpl;
	}

	@Override
	public int compareTo(Lectureseries_Facility lectureseries_Facility) {
		long primaryKey = lectureseries_Facility.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Lectureseries_Facility)) {
			return false;
		}

		Lectureseries_Facility lectureseries_Facility = (Lectureseries_Facility)obj;

		long primaryKey = lectureseries_Facility.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Lectureseries_Facility> toCacheModel() {
		Lectureseries_FacilityCacheModel lectureseries_FacilityCacheModel = new Lectureseries_FacilityCacheModel();

		lectureseries_FacilityCacheModel.lectureseriesFacilityId = getLectureseriesFacilityId();

		lectureseries_FacilityCacheModel.lectureseriesId = getLectureseriesId();

		lectureseries_FacilityCacheModel.facilityId = getFacilityId();

		return lectureseries_FacilityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{lectureseriesFacilityId=");
		sb.append(getLectureseriesFacilityId());
		sb.append(", lectureseriesId=");
		sb.append(getLectureseriesId());
		sb.append(", facilityId=");
		sb.append(getFacilityId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.model.Lectureseries_Facility");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>lectureseriesFacilityId</column-name><column-value><![CDATA[");
		sb.append(getLectureseriesFacilityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lectureseriesId</column-name><column-value><![CDATA[");
		sb.append(getLectureseriesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facilityId</column-name><column-value><![CDATA[");
		sb.append(getFacilityId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Lectureseries_Facility.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Lectureseries_Facility.class
		};
	private long _lectureseriesFacilityId;
	private long _lectureseriesId;
	private long _facilityId;
	private Lectureseries_Facility _escapedModel;
}