/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.uhh.l2g.plugins.model.Lectureseries_Institution;
import de.uhh.l2g.plugins.service.Lectureseries_InstitutionLocalServiceUtil;

/**
 * The extended model base implementation for the Lectureseries_Institution service. Represents a row in the &quot;LG_Lectureseries_Institution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Lectureseries_InstitutionImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Lectureseries_InstitutionImpl
 * @see de.uhh.l2g.plugins.model.Lectureseries_Institution
 * @generated
 */
public abstract class Lectureseries_InstitutionBaseImpl
	extends Lectureseries_InstitutionModelImpl
	implements Lectureseries_Institution {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lectureseries_ institution model instance should use the {@link Lectureseries_Institution} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			Lectureseries_InstitutionLocalServiceUtil.addLectureseries_Institution(this);
		}
		else {
			Lectureseries_InstitutionLocalServiceUtil.updateLectureseries_Institution(this);
		}
	}
}