/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import de.uhh.l2g.plugins.model.License;
import de.uhh.l2g.plugins.model.LicenseModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the License service. Represents a row in the &quot;LG_License&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.model.LicenseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see LicenseImpl
 * @see de.uhh.l2g.plugins.model.License
 * @see de.uhh.l2g.plugins.model.LicenseModel
 * @generated
 */
public class LicenseModelImpl extends BaseModelImpl<License>
	implements LicenseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license model instance should use the {@link de.uhh.l2g.plugins.model.License} interface instead.
	 */
	public static final String TABLE_NAME = "LG_License";
	public static final Object[][] TABLE_COLUMNS = {
			{ "licenseId", Types.INTEGER },
			{ "videoId", Types.INTEGER },
			{ "ccby", Types.VARCHAR },
			{ "ccbybc", Types.VARCHAR },
			{ "ccbyncnd", Types.VARCHAR },
			{ "ccbyncsa", Types.VARCHAR },
			{ "ccbysa", Types.VARCHAR },
			{ "ccbync", Types.VARCHAR },
			{ "l2go", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table LG_License (licenseId INTEGER not null primary key,videoId INTEGER,ccby VARCHAR(75) null,ccbybc VARCHAR(75) null,ccbyncnd VARCHAR(75) null,ccbyncsa VARCHAR(75) null,ccbysa VARCHAR(75) null,ccbync VARCHAR(75) null,l2go VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table LG_License";
	public static final String ORDER_BY_JPQL = " ORDER BY license.licenseId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LG_License.licenseId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.License"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.License"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.model.License"));

	public LicenseModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _licenseId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setLicenseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _licenseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return License.class;
	}

	@Override
	public String getModelClassName() {
		return License.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("licenseId", getLicenseId());
		attributes.put("videoId", getVideoId());
		attributes.put("ccby", getCcby());
		attributes.put("ccbybc", getCcbybc());
		attributes.put("ccbyncnd", getCcbyncnd());
		attributes.put("ccbyncsa", getCcbyncsa());
		attributes.put("ccbysa", getCcbysa());
		attributes.put("ccbync", getCcbync());
		attributes.put("l2go", getL2go());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer licenseId = (Integer)attributes.get("licenseId");

		if (licenseId != null) {
			setLicenseId(licenseId);
		}

		Integer videoId = (Integer)attributes.get("videoId");

		if (videoId != null) {
			setVideoId(videoId);
		}

		String ccby = (String)attributes.get("ccby");

		if (ccby != null) {
			setCcby(ccby);
		}

		String ccbybc = (String)attributes.get("ccbybc");

		if (ccbybc != null) {
			setCcbybc(ccbybc);
		}

		String ccbyncnd = (String)attributes.get("ccbyncnd");

		if (ccbyncnd != null) {
			setCcbyncnd(ccbyncnd);
		}

		String ccbyncsa = (String)attributes.get("ccbyncsa");

		if (ccbyncsa != null) {
			setCcbyncsa(ccbyncsa);
		}

		String ccbysa = (String)attributes.get("ccbysa");

		if (ccbysa != null) {
			setCcbysa(ccbysa);
		}

		String ccbync = (String)attributes.get("ccbync");

		if (ccbync != null) {
			setCcbync(ccbync);
		}

		String l2go = (String)attributes.get("l2go");

		if (l2go != null) {
			setL2go(l2go);
		}
	}

	@Override
	public int getLicenseId() {
		return _licenseId;
	}

	@Override
	public void setLicenseId(int licenseId) {
		_licenseId = licenseId;
	}

	@Override
	public int getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(int videoId) {
		_videoId = videoId;
	}

	@Override
	public String getCcby() {
		if (_ccby == null) {
			return StringPool.BLANK;
		}
		else {
			return _ccby;
		}
	}

	@Override
	public void setCcby(String ccby) {
		_ccby = ccby;
	}

	@Override
	public String getCcbybc() {
		if (_ccbybc == null) {
			return StringPool.BLANK;
		}
		else {
			return _ccbybc;
		}
	}

	@Override
	public void setCcbybc(String ccbybc) {
		_ccbybc = ccbybc;
	}

	@Override
	public String getCcbyncnd() {
		if (_ccbyncnd == null) {
			return StringPool.BLANK;
		}
		else {
			return _ccbyncnd;
		}
	}

	@Override
	public void setCcbyncnd(String ccbyncnd) {
		_ccbyncnd = ccbyncnd;
	}

	@Override
	public String getCcbyncsa() {
		if (_ccbyncsa == null) {
			return StringPool.BLANK;
		}
		else {
			return _ccbyncsa;
		}
	}

	@Override
	public void setCcbyncsa(String ccbyncsa) {
		_ccbyncsa = ccbyncsa;
	}

	@Override
	public String getCcbysa() {
		if (_ccbysa == null) {
			return StringPool.BLANK;
		}
		else {
			return _ccbysa;
		}
	}

	@Override
	public void setCcbysa(String ccbysa) {
		_ccbysa = ccbysa;
	}

	@Override
	public String getCcbync() {
		if (_ccbync == null) {
			return StringPool.BLANK;
		}
		else {
			return _ccbync;
		}
	}

	@Override
	public void setCcbync(String ccbync) {
		_ccbync = ccbync;
	}

	@Override
	public String getL2go() {
		if (_l2go == null) {
			return StringPool.BLANK;
		}
		else {
			return _l2go;
		}
	}

	@Override
	public void setL2go(String l2go) {
		_l2go = l2go;
	}

	@Override
	public License toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (License)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LicenseImpl licenseImpl = new LicenseImpl();

		licenseImpl.setLicenseId(getLicenseId());
		licenseImpl.setVideoId(getVideoId());
		licenseImpl.setCcby(getCcby());
		licenseImpl.setCcbybc(getCcbybc());
		licenseImpl.setCcbyncnd(getCcbyncnd());
		licenseImpl.setCcbyncsa(getCcbyncsa());
		licenseImpl.setCcbysa(getCcbysa());
		licenseImpl.setCcbync(getCcbync());
		licenseImpl.setL2go(getL2go());

		licenseImpl.resetOriginalValues();

		return licenseImpl;
	}

	@Override
	public int compareTo(License license) {
		int primaryKey = license.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof License)) {
			return false;
		}

		License license = (License)obj;

		int primaryKey = license.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<License> toCacheModel() {
		LicenseCacheModel licenseCacheModel = new LicenseCacheModel();

		licenseCacheModel.licenseId = getLicenseId();

		licenseCacheModel.videoId = getVideoId();

		licenseCacheModel.ccby = getCcby();

		String ccby = licenseCacheModel.ccby;

		if ((ccby != null) && (ccby.length() == 0)) {
			licenseCacheModel.ccby = null;
		}

		licenseCacheModel.ccbybc = getCcbybc();

		String ccbybc = licenseCacheModel.ccbybc;

		if ((ccbybc != null) && (ccbybc.length() == 0)) {
			licenseCacheModel.ccbybc = null;
		}

		licenseCacheModel.ccbyncnd = getCcbyncnd();

		String ccbyncnd = licenseCacheModel.ccbyncnd;

		if ((ccbyncnd != null) && (ccbyncnd.length() == 0)) {
			licenseCacheModel.ccbyncnd = null;
		}

		licenseCacheModel.ccbyncsa = getCcbyncsa();

		String ccbyncsa = licenseCacheModel.ccbyncsa;

		if ((ccbyncsa != null) && (ccbyncsa.length() == 0)) {
			licenseCacheModel.ccbyncsa = null;
		}

		licenseCacheModel.ccbysa = getCcbysa();

		String ccbysa = licenseCacheModel.ccbysa;

		if ((ccbysa != null) && (ccbysa.length() == 0)) {
			licenseCacheModel.ccbysa = null;
		}

		licenseCacheModel.ccbync = getCcbync();

		String ccbync = licenseCacheModel.ccbync;

		if ((ccbync != null) && (ccbync.length() == 0)) {
			licenseCacheModel.ccbync = null;
		}

		licenseCacheModel.l2go = getL2go();

		String l2go = licenseCacheModel.l2go;

		if ((l2go != null) && (l2go.length() == 0)) {
			licenseCacheModel.l2go = null;
		}

		return licenseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{licenseId=");
		sb.append(getLicenseId());
		sb.append(", videoId=");
		sb.append(getVideoId());
		sb.append(", ccby=");
		sb.append(getCcby());
		sb.append(", ccbybc=");
		sb.append(getCcbybc());
		sb.append(", ccbyncnd=");
		sb.append(getCcbyncnd());
		sb.append(", ccbyncsa=");
		sb.append(getCcbyncsa());
		sb.append(", ccbysa=");
		sb.append(getCcbysa());
		sb.append(", ccbync=");
		sb.append(getCcbync());
		sb.append(", l2go=");
		sb.append(getL2go());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.model.License");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>licenseId</column-name><column-value><![CDATA[");
		sb.append(getLicenseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoId</column-name><column-value><![CDATA[");
		sb.append(getVideoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccby</column-name><column-value><![CDATA[");
		sb.append(getCcby());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbybc</column-name><column-value><![CDATA[");
		sb.append(getCcbybc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbyncnd</column-name><column-value><![CDATA[");
		sb.append(getCcbyncnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbyncsa</column-name><column-value><![CDATA[");
		sb.append(getCcbyncsa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbysa</column-name><column-value><![CDATA[");
		sb.append(getCcbysa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccbync</column-name><column-value><![CDATA[");
		sb.append(getCcbync());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>l2go</column-name><column-value><![CDATA[");
		sb.append(getL2go());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = License.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			License.class
		};
	private int _licenseId;
	private int _videoId;
	private String _ccby;
	private String _ccbybc;
	private String _ccbyncnd;
	private String _ccbyncsa;
	private String _ccbysa;
	private String _ccbync;
	private String _l2go;
	private License _escapedModel;
}