/*******************************************************************************
 * License
 * 
 * +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++
 * 
 * Lecture2Go 
 * 
 * The Lecture2Go software is based on the liferay portal 6.2-ga6
 * <http://www.liferay.com> (Copyright notice see below)
 * Lecture2Go <http://lecture2go.uni-hamburg.de> is an open source
 * platform for media management and distribution. Our goal is to
 * support the free access to knowledge because this is a component
 * of each democratic society. The open source software is aimed at
 * academic institutions and has to strengthen the blended learning.
 * All Lecture2Go plugins are continuously being developed and improved.
 * For more details please visit <http://lecture2go-open-source.rrz.uni-hamburg.de>
 * Copyright (c) 2013 - present University of Hamburg / Computer and Data Center (RRZ)
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *  
 * +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++
 * 
 * The Liferay Plugins SDK:
 * 
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 * 
 * +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++ +++
 * 
 * Third Party Software
 * 
 * Lecture2Go uses third-party libraries which may be distributed under different licenses
 * to the above (but are compatible with the used GPL license). Informations about these
 * licenses and copyright informations are mostly detailed in the library source code or jars themselves.
 * You must agree to the terms of these licenses, in addition tothe above Lecture2Go source code license,
 * in order to use this software.
 ******************************************************************************/
/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.uhh.l2g.plugins.model.Video_Institution;
import de.uhh.l2g.plugins.model.Video_InstitutionModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Video_Institution service. Represents a row in the &quot;LG_Video_Institution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.model.Video_InstitutionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Video_InstitutionImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_InstitutionImpl
 * @see de.uhh.l2g.plugins.model.Video_Institution
 * @see de.uhh.l2g.plugins.model.Video_InstitutionModel
 * @generated
 */
public class Video_InstitutionModelImpl extends BaseModelImpl<Video_Institution>
	implements Video_InstitutionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video_ institution model instance should use the {@link de.uhh.l2g.plugins.model.Video_Institution} interface instead.
	 */
	public static final String TABLE_NAME = "LG_Video_Institution";
	public static final Object[][] TABLE_COLUMNS = {
			{ "videoInstitutionId", Types.BIGINT },
			{ "videoId", Types.BIGINT },
			{ "institutionId", Types.BIGINT },
			{ "institutionParentId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table LG_Video_Institution (videoInstitutionId LONG not null primary key,videoId LONG,institutionId LONG,institutionParentId LONG)";
	public static final String TABLE_SQL_DROP = "drop table LG_Video_Institution";
	public static final String ORDER_BY_JPQL = " ORDER BY video_Institution.videoInstitutionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LG_Video_Institution.videoInstitutionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Video_Institution"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Video_Institution"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Video_Institution"),
			true);
	public static long INSTITUTIONID_COLUMN_BITMASK = 1L;
	public static long INSTITUTIONPARENTID_COLUMN_BITMASK = 2L;
	public static long VIDEOID_COLUMN_BITMASK = 4L;
	public static long VIDEOINSTITUTIONID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.model.Video_Institution"));

	public Video_InstitutionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _videoInstitutionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVideoInstitutionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _videoInstitutionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Video_Institution.class;
	}

	@Override
	public String getModelClassName() {
		return Video_Institution.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("videoInstitutionId", getVideoInstitutionId());
		attributes.put("videoId", getVideoId());
		attributes.put("institutionId", getInstitutionId());
		attributes.put("institutionParentId", getInstitutionParentId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long videoInstitutionId = (Long)attributes.get("videoInstitutionId");

		if (videoInstitutionId != null) {
			setVideoInstitutionId(videoInstitutionId);
		}

		Long videoId = (Long)attributes.get("videoId");

		if (videoId != null) {
			setVideoId(videoId);
		}

		Long institutionId = (Long)attributes.get("institutionId");

		if (institutionId != null) {
			setInstitutionId(institutionId);
		}

		Long institutionParentId = (Long)attributes.get("institutionParentId");

		if (institutionParentId != null) {
			setInstitutionParentId(institutionParentId);
		}
	}

	@Override
	public long getVideoInstitutionId() {
		return _videoInstitutionId;
	}

	@Override
	public void setVideoInstitutionId(long videoInstitutionId) {
		_videoInstitutionId = videoInstitutionId;
	}

	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_columnBitmask |= VIDEOID_COLUMN_BITMASK;

		if (!_setOriginalVideoId) {
			_setOriginalVideoId = true;

			_originalVideoId = _videoId;
		}

		_videoId = videoId;
	}

	public long getOriginalVideoId() {
		return _originalVideoId;
	}

	@Override
	public long getInstitutionId() {
		return _institutionId;
	}

	@Override
	public void setInstitutionId(long institutionId) {
		_columnBitmask |= INSTITUTIONID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionId) {
			_setOriginalInstitutionId = true;

			_originalInstitutionId = _institutionId;
		}

		_institutionId = institutionId;
	}

	public long getOriginalInstitutionId() {
		return _originalInstitutionId;
	}

	@Override
	public long getInstitutionParentId() {
		return _institutionParentId;
	}

	@Override
	public void setInstitutionParentId(long institutionParentId) {
		_columnBitmask |= INSTITUTIONPARENTID_COLUMN_BITMASK;

		if (!_setOriginalInstitutionParentId) {
			_setOriginalInstitutionParentId = true;

			_originalInstitutionParentId = _institutionParentId;
		}

		_institutionParentId = institutionParentId;
	}

	public long getOriginalInstitutionParentId() {
		return _originalInstitutionParentId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Video_Institution.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Video_Institution toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Video_Institution)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Video_InstitutionImpl video_InstitutionImpl = new Video_InstitutionImpl();

		video_InstitutionImpl.setVideoInstitutionId(getVideoInstitutionId());
		video_InstitutionImpl.setVideoId(getVideoId());
		video_InstitutionImpl.setInstitutionId(getInstitutionId());
		video_InstitutionImpl.setInstitutionParentId(getInstitutionParentId());

		video_InstitutionImpl.resetOriginalValues();

		return video_InstitutionImpl;
	}

	@Override
	public int compareTo(Video_Institution video_Institution) {
		long primaryKey = video_Institution.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Video_Institution)) {
			return false;
		}

		Video_Institution video_Institution = (Video_Institution)obj;

		long primaryKey = video_Institution.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		Video_InstitutionModelImpl video_InstitutionModelImpl = this;

		video_InstitutionModelImpl._originalVideoId = video_InstitutionModelImpl._videoId;

		video_InstitutionModelImpl._setOriginalVideoId = false;

		video_InstitutionModelImpl._originalInstitutionId = video_InstitutionModelImpl._institutionId;

		video_InstitutionModelImpl._setOriginalInstitutionId = false;

		video_InstitutionModelImpl._originalInstitutionParentId = video_InstitutionModelImpl._institutionParentId;

		video_InstitutionModelImpl._setOriginalInstitutionParentId = false;

		video_InstitutionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Video_Institution> toCacheModel() {
		Video_InstitutionCacheModel video_InstitutionCacheModel = new Video_InstitutionCacheModel();

		video_InstitutionCacheModel.videoInstitutionId = getVideoInstitutionId();

		video_InstitutionCacheModel.videoId = getVideoId();

		video_InstitutionCacheModel.institutionId = getInstitutionId();

		video_InstitutionCacheModel.institutionParentId = getInstitutionParentId();

		return video_InstitutionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{videoInstitutionId=");
		sb.append(getVideoInstitutionId());
		sb.append(", videoId=");
		sb.append(getVideoId());
		sb.append(", institutionId=");
		sb.append(getInstitutionId());
		sb.append(", institutionParentId=");
		sb.append(getInstitutionParentId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.model.Video_Institution");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>videoInstitutionId</column-name><column-value><![CDATA[");
		sb.append(getVideoInstitutionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoId</column-name><column-value><![CDATA[");
		sb.append(getVideoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>institutionId</column-name><column-value><![CDATA[");
		sb.append(getInstitutionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>institutionParentId</column-name><column-value><![CDATA[");
		sb.append(getInstitutionParentId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Video_Institution.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Video_Institution.class
		};
	private long _videoInstitutionId;
	private long _videoId;
	private long _originalVideoId;
	private boolean _setOriginalVideoId;
	private long _institutionId;
	private long _originalInstitutionId;
	private boolean _setOriginalInstitutionId;
	private long _institutionParentId;
	private long _originalInstitutionParentId;
	private boolean _setOriginalInstitutionParentId;
	private long _columnBitmask;
	private Video_Institution _escapedModel;
}
