/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.uhh.l2g.plugins.model.Video_Facility;
import de.uhh.l2g.plugins.model.Video_FacilityModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Video_Facility service. Represents a row in the &quot;LG_Video_Facility&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.model.Video_FacilityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Video_FacilityImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_FacilityImpl
 * @see de.uhh.l2g.plugins.model.Video_Facility
 * @see de.uhh.l2g.plugins.model.Video_FacilityModel
 * @generated
 */
public class Video_FacilityModelImpl extends BaseModelImpl<Video_Facility>
	implements Video_FacilityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video_ facility model instance should use the {@link de.uhh.l2g.plugins.model.Video_Facility} interface instead.
	 */
	public static final String TABLE_NAME = "LG_Video_Facility";
	public static final Object[][] TABLE_COLUMNS = {
			{ "videoFacilityId", Types.BIGINT },
			{ "videoId", Types.BIGINT },
			{ "facilityId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table LG_Video_Facility (videoFacilityId LONG not null primary key,videoId LONG,facilityId LONG)";
	public static final String TABLE_SQL_DROP = "drop table LG_Video_Facility";
	public static final String ORDER_BY_JPQL = " ORDER BY video_Facility.videoFacilityId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LG_Video_Facility.videoFacilityId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Video_Facility"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Video_Facility"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.model.Video_Facility"));

	public Video_FacilityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _videoFacilityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVideoFacilityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _videoFacilityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Video_Facility.class;
	}

	@Override
	public String getModelClassName() {
		return Video_Facility.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("videoFacilityId", getVideoFacilityId());
		attributes.put("videoId", getVideoId());
		attributes.put("facilityId", getFacilityId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long videoFacilityId = (Long)attributes.get("videoFacilityId");

		if (videoFacilityId != null) {
			setVideoFacilityId(videoFacilityId);
		}

		Long videoId = (Long)attributes.get("videoId");

		if (videoId != null) {
			setVideoId(videoId);
		}

		Long facilityId = (Long)attributes.get("facilityId");

		if (facilityId != null) {
			setFacilityId(facilityId);
		}
	}

	@Override
	public long getVideoFacilityId() {
		return _videoFacilityId;
	}

	@Override
	public void setVideoFacilityId(long videoFacilityId) {
		_videoFacilityId = videoFacilityId;
	}

	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		_videoId = videoId;
	}

	@Override
	public long getFacilityId() {
		return _facilityId;
	}

	@Override
	public void setFacilityId(long facilityId) {
		_facilityId = facilityId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Video_Facility.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Video_Facility toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Video_Facility)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Video_FacilityImpl video_FacilityImpl = new Video_FacilityImpl();

		video_FacilityImpl.setVideoFacilityId(getVideoFacilityId());
		video_FacilityImpl.setVideoId(getVideoId());
		video_FacilityImpl.setFacilityId(getFacilityId());

		video_FacilityImpl.resetOriginalValues();

		return video_FacilityImpl;
	}

	@Override
	public int compareTo(Video_Facility video_Facility) {
		long primaryKey = video_Facility.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Video_Facility)) {
			return false;
		}

		Video_Facility video_Facility = (Video_Facility)obj;

		long primaryKey = video_Facility.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Video_Facility> toCacheModel() {
		Video_FacilityCacheModel video_FacilityCacheModel = new Video_FacilityCacheModel();

		video_FacilityCacheModel.videoFacilityId = getVideoFacilityId();

		video_FacilityCacheModel.videoId = getVideoId();

		video_FacilityCacheModel.facilityId = getFacilityId();

		return video_FacilityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{videoFacilityId=");
		sb.append(getVideoFacilityId());
		sb.append(", videoId=");
		sb.append(getVideoId());
		sb.append(", facilityId=");
		sb.append(getFacilityId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.model.Video_Facility");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>videoFacilityId</column-name><column-value><![CDATA[");
		sb.append(getVideoFacilityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>videoId</column-name><column-value><![CDATA[");
		sb.append(getVideoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facilityId</column-name><column-value><![CDATA[");
		sb.append(getFacilityId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Video_Facility.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Video_Facility.class
		};
	private long _videoFacilityId;
	private long _videoId;
	private long _facilityId;
	private Video_Facility _escapedModel;
}