/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.uhh.l2g.plugins.model.Video_Creator;
import de.uhh.l2g.plugins.model.Video_CreatorModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Video_Creator service. Represents a row in the &quot;LG_Video_Creator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.model.Video_CreatorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Video_CreatorImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_CreatorImpl
 * @see de.uhh.l2g.plugins.model.Video_Creator
 * @see de.uhh.l2g.plugins.model.Video_CreatorModel
 * @generated
 */
public class Video_CreatorModelImpl extends BaseModelImpl<Video_Creator>
	implements Video_CreatorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video_ creator model instance should use the {@link de.uhh.l2g.plugins.model.Video_Creator} interface instead.
	 */
	public static final String TABLE_NAME = "LG_Video_Creator";
	public static final Object[][] TABLE_COLUMNS = {
			{ "videoCreatorId", Types.BIGINT },
			{ "creatorId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table LG_Video_Creator (videoCreatorId LONG not null primary key,creatorId LONG)";
	public static final String TABLE_SQL_DROP = "drop table LG_Video_Creator";
	public static final String ORDER_BY_JPQL = " ORDER BY video_Creator.videoCreatorId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LG_Video_Creator.videoCreatorId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Video_Creator"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Video_Creator"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.model.Video_Creator"));

	public Video_CreatorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _videoCreatorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVideoCreatorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _videoCreatorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Video_Creator.class;
	}

	@Override
	public String getModelClassName() {
		return Video_Creator.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("videoCreatorId", getVideoCreatorId());
		attributes.put("creatorId", getCreatorId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long videoCreatorId = (Long)attributes.get("videoCreatorId");

		if (videoCreatorId != null) {
			setVideoCreatorId(videoCreatorId);
		}

		Long creatorId = (Long)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}
	}

	@Override
	public long getVideoCreatorId() {
		return _videoCreatorId;
	}

	@Override
	public void setVideoCreatorId(long videoCreatorId) {
		_videoCreatorId = videoCreatorId;
	}

	@Override
	public long getCreatorId() {
		return _creatorId;
	}

	@Override
	public void setCreatorId(long creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Video_Creator.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Video_Creator toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Video_Creator)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Video_CreatorImpl video_CreatorImpl = new Video_CreatorImpl();

		video_CreatorImpl.setVideoCreatorId(getVideoCreatorId());
		video_CreatorImpl.setCreatorId(getCreatorId());

		video_CreatorImpl.resetOriginalValues();

		return video_CreatorImpl;
	}

	@Override
	public int compareTo(Video_Creator video_Creator) {
		long primaryKey = video_Creator.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Video_Creator)) {
			return false;
		}

		Video_Creator video_Creator = (Video_Creator)obj;

		long primaryKey = video_Creator.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Video_Creator> toCacheModel() {
		Video_CreatorCacheModel video_CreatorCacheModel = new Video_CreatorCacheModel();

		video_CreatorCacheModel.videoCreatorId = getVideoCreatorId();

		video_CreatorCacheModel.creatorId = getCreatorId();

		return video_CreatorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{videoCreatorId=");
		sb.append(getVideoCreatorId());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.model.Video_Creator");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>videoCreatorId</column-name><column-value><![CDATA[");
		sb.append(getVideoCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Video_Creator.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Video_Creator.class
		};
	private long _videoCreatorId;
	private long _creatorId;
	private Video_Creator _escapedModel;
}