/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import de.uhh.l2g.plugins.model.Year;
import de.uhh.l2g.plugins.model.YearModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Year service. Represents a row in the &quot;LG_Year&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.uhh.l2g.plugins.model.YearModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link YearImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see YearImpl
 * @see de.uhh.l2g.plugins.model.Year
 * @see de.uhh.l2g.plugins.model.YearModel
 * @generated
 */
public class YearModelImpl extends BaseModelImpl<Year> implements YearModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a year model instance should use the {@link de.uhh.l2g.plugins.model.Year} interface instead.
	 */
	public static final String TABLE_NAME = "LG_Year";
	public static final Object[][] TABLE_COLUMNS = {
			{ "yearId", Types.BIGINT },
			{ "parentId", Types.BIGINT },
			{ "languageId", Types.VARCHAR },
			{ "prefix", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "translation", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table LG_Year (yearId LONG not null primary key,parentId LONG,languageId VARCHAR(75) null,prefix VARCHAR(75) null,name VARCHAR(75) null,translation VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table LG_Year";
	public static final String ORDER_BY_JPQL = " ORDER BY year.yearId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LG_Year.yearId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.uhh.l2g.plugins.model.Year"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.uhh.l2g.plugins.model.Year"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.de.uhh.l2g.plugins.model.Year"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;
	public static long PREFIX_COLUMN_BITMASK = 2L;
	public static long YEARID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.uhh.l2g.plugins.model.Year"));

	public YearModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _yearId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setYearId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _yearId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Year.class;
	}

	@Override
	public String getModelClassName() {
		return Year.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("yearId", getYearId());
		attributes.put("parentId", getParentId());
		attributes.put("languageId", getLanguageId());
		attributes.put("prefix", getPrefix());
		attributes.put("name", getName());
		attributes.put("translation", getTranslation());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long yearId = (Long)attributes.get("yearId");

		if (yearId != null) {
			setYearId(yearId);
		}

		Long parentId = (Long)attributes.get("parentId");

		if (parentId != null) {
			setParentId(parentId);
		}

		String languageId = (String)attributes.get("languageId");

		if (languageId != null) {
			setLanguageId(languageId);
		}

		String prefix = (String)attributes.get("prefix");

		if (prefix != null) {
			setPrefix(prefix);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String translation = (String)attributes.get("translation");

		if (translation != null) {
			setTranslation(translation);
		}
	}

	@Override
	public long getYearId() {
		return _yearId;
	}

	@Override
	public void setYearId(long yearId) {
		_yearId = yearId;
	}

	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		_parentId = parentId;
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		_languageId = languageId;
	}

	@Override
	public String getPrefix() {
		if (_prefix == null) {
			return StringPool.BLANK;
		}
		else {
			return _prefix;
		}
	}

	@Override
	public void setPrefix(String prefix) {
		_columnBitmask |= PREFIX_COLUMN_BITMASK;

		if (_originalPrefix == null) {
			_originalPrefix = _prefix;
		}

		_prefix = prefix;
	}

	public String getOriginalPrefix() {
		return GetterUtil.getString(_originalPrefix);
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public String getTranslation() {
		if (_translation == null) {
			return StringPool.BLANK;
		}
		else {
			return _translation;
		}
	}

	@Override
	public void setTranslation(String translation) {
		_translation = translation;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Year.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Year toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Year)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		YearImpl yearImpl = new YearImpl();

		yearImpl.setYearId(getYearId());
		yearImpl.setParentId(getParentId());
		yearImpl.setLanguageId(getLanguageId());
		yearImpl.setPrefix(getPrefix());
		yearImpl.setName(getName());
		yearImpl.setTranslation(getTranslation());

		yearImpl.resetOriginalValues();

		return yearImpl;
	}

	@Override
	public int compareTo(Year year) {
		long primaryKey = year.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Year)) {
			return false;
		}

		Year year = (Year)obj;

		long primaryKey = year.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		YearModelImpl yearModelImpl = this;

		yearModelImpl._originalPrefix = yearModelImpl._prefix;

		yearModelImpl._originalName = yearModelImpl._name;

		yearModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Year> toCacheModel() {
		YearCacheModel yearCacheModel = new YearCacheModel();

		yearCacheModel.yearId = getYearId();

		yearCacheModel.parentId = getParentId();

		yearCacheModel.languageId = getLanguageId();

		String languageId = yearCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			yearCacheModel.languageId = null;
		}

		yearCacheModel.prefix = getPrefix();

		String prefix = yearCacheModel.prefix;

		if ((prefix != null) && (prefix.length() == 0)) {
			yearCacheModel.prefix = null;
		}

		yearCacheModel.name = getName();

		String name = yearCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			yearCacheModel.name = null;
		}

		yearCacheModel.translation = getTranslation();

		String translation = yearCacheModel.translation;

		if ((translation != null) && (translation.length() == 0)) {
			yearCacheModel.translation = null;
		}

		return yearCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{yearId=");
		sb.append(getYearId());
		sb.append(", parentId=");
		sb.append(getParentId());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append(", prefix=");
		sb.append(getPrefix());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", translation=");
		sb.append(getTranslation());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("de.uhh.l2g.plugins.model.Year");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>yearId</column-name><column-value><![CDATA[");
		sb.append(getYearId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentId</column-name><column-value><![CDATA[");
		sb.append(getParentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>prefix</column-name><column-value><![CDATA[");
		sb.append(getPrefix());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>translation</column-name><column-value><![CDATA[");
		sb.append(getTranslation());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Year.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Year.class };
	private long _yearId;
	private long _parentId;
	private String _languageId;
	private String _prefix;
	private String _originalPrefix;
	private String _name;
	private String _originalName;
	private String _translation;
	private long _columnBitmask;
	private Year _escapedModel;
}