/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LegacyLastVideoList service. Represents a row in the &quot;lastvideolist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyLastVideoListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyLastVideoListImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyLastVideoList
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyLastVideoListImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyLastVideoListModelImpl
 * @generated
 */
public interface LegacyLastVideoListModel extends BaseModel<LegacyLastVideoList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy last video list model instance should use the {@link LegacyLastVideoList} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy last video list.
	 *
	 * @return the primary key of this legacy last video list
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this legacy last video list.
	 *
	 * @param primaryKey the primary key of this legacy last video list
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this legacy last video list.
	 *
	 * @return the ID of this legacy last video list
	 */
	public int getId();

	/**
	 * Sets the ID of this legacy last video list.
	 *
	 * @param id the ID of this legacy last video list
	 */
	public void setId(int id);

	/**
	 * Returns the video ID of this legacy last video list.
	 *
	 * @return the video ID of this legacy last video list
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this legacy last video list.
	 *
	 * @param videoId the video ID of this legacy last video list
	 */
	public void setVideoId(long videoId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LegacyLastVideoList legacyLastVideoList);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LegacyLastVideoList> toCacheModel();

	@Override
	public LegacyLastVideoList toEscapedModel();

	@Override
	public LegacyLastVideoList toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}