/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LegacyStatistic service. Represents a row in the &quot;videostats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyStatisticModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyStatisticImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyStatistic
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyStatisticImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyStatisticModelImpl
 * @generated
 */
public interface LegacyStatisticModel extends BaseModel<LegacyStatistic> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy statistic model instance should use the {@link LegacyStatistic} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy statistic.
	 *
	 * @return the primary key of this legacy statistic
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this legacy statistic.
	 *
	 * @param primaryKey the primary key of this legacy statistic
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this legacy statistic.
	 *
	 * @return the ID of this legacy statistic
	 */
	public int getId();

	/**
	 * Sets the ID of this legacy statistic.
	 *
	 * @param id the ID of this legacy statistic
	 */
	public void setId(int id);

	/**
	 * Returns the public_ of this legacy statistic.
	 *
	 * @return the public_ of this legacy statistic
	 */
	public int getPublic_();

	/**
	 * Sets the public_ of this legacy statistic.
	 *
	 * @param public_ the public_ of this legacy statistic
	 */
	public void setPublic_(int public_);

	/**
	 * Returns the private_ of this legacy statistic.
	 *
	 * @return the private_ of this legacy statistic
	 */
	public int getPrivate_();

	/**
	 * Sets the private_ of this legacy statistic.
	 *
	 * @param private_ the private_ of this legacy statistic
	 */
	public void setPrivate_(int private_);

	/**
	 * Returns the autofill of this legacy statistic.
	 *
	 * @return the autofill of this legacy statistic
	 */
	public int getAutofill();

	/**
	 * Sets the autofill of this legacy statistic.
	 *
	 * @param autofill the autofill of this legacy statistic
	 */
	public void setAutofill(int autofill);

	/**
	 * Returns the date_ of this legacy statistic.
	 *
	 * @return the date_ of this legacy statistic
	 */
	public Date getDate_();

	/**
	 * Sets the date_ of this legacy statistic.
	 *
	 * @param date_ the date_ of this legacy statistic
	 */
	public void setDate_(Date date_);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.uhh.l2g.plugins.migration.model.LegacyStatistic legacyStatistic);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.migration.model.LegacyStatistic> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyStatistic toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyStatistic toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}