/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LegacyVideo service. Represents a row in the &quot;video&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyVideoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyVideoImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyVideo
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyVideoImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyVideoModelImpl
 * @generated
 */
public interface LegacyVideoModel extends BaseModel<LegacyVideo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy video model instance should use the {@link LegacyVideo} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy video.
	 *
	 * @return the primary key of this legacy video
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacy video.
	 *
	 * @param primaryKey the primary key of this legacy video
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this legacy video.
	 *
	 * @return the ID of this legacy video
	 */
	public long getId();

	/**
	 * Sets the ID of this legacy video.
	 *
	 * @param id the ID of this legacy video
	 */
	public void setId(long id);

	/**
	 * Returns the title of this legacy video.
	 *
	 * @return the title of this legacy video
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this legacy video.
	 *
	 * @param title the title of this legacy video
	 */
	public void setTitle(String title);

	/**
	 * Returns the tags of this legacy video.
	 *
	 * @return the tags of this legacy video
	 */
	@AutoEscape
	public String getTags();

	/**
	 * Sets the tags of this legacy video.
	 *
	 * @param tags the tags of this legacy video
	 */
	public void setTags(String tags);

	/**
	 * Returns the lectureseries ID of this legacy video.
	 *
	 * @return the lectureseries ID of this legacy video
	 */
	public long getLectureseriesId();

	/**
	 * Sets the lectureseries ID of this legacy video.
	 *
	 * @param lectureseriesId the lectureseries ID of this legacy video
	 */
	public void setLectureseriesId(long lectureseriesId);

	/**
	 * Returns the owner ID of this legacy video.
	 *
	 * @return the owner ID of this legacy video
	 */
	public long getOwnerId();

	/**
	 * Sets the owner ID of this legacy video.
	 *
	 * @param ownerId the owner ID of this legacy video
	 */
	public void setOwnerId(long ownerId);

	/**
	 * Returns the producer ID of this legacy video.
	 *
	 * @return the producer ID of this legacy video
	 */
	public long getProducerId();

	/**
	 * Sets the producer ID of this legacy video.
	 *
	 * @param producerId the producer ID of this legacy video
	 */
	public void setProducerId(long producerId);

	/**
	 * Returns the container format of this legacy video.
	 *
	 * @return the container format of this legacy video
	 */
	@AutoEscape
	public String getContainerFormat();

	/**
	 * Sets the container format of this legacy video.
	 *
	 * @param containerFormat the container format of this legacy video
	 */
	public void setContainerFormat(String containerFormat);

	/**
	 * Returns the filename of this legacy video.
	 *
	 * @return the filename of this legacy video
	 */
	@AutoEscape
	public String getFilename();

	/**
	 * Sets the filename of this legacy video.
	 *
	 * @param filename the filename of this legacy video
	 */
	public void setFilename(String filename);

	/**
	 * Returns the resolution of this legacy video.
	 *
	 * @return the resolution of this legacy video
	 */
	@AutoEscape
	public String getResolution();

	/**
	 * Sets the resolution of this legacy video.
	 *
	 * @param resolution the resolution of this legacy video
	 */
	public void setResolution(String resolution);

	/**
	 * Returns the duration of this legacy video.
	 *
	 * @return the duration of this legacy video
	 */
	@AutoEscape
	public String getDuration();

	/**
	 * Sets the duration of this legacy video.
	 *
	 * @param duration the duration of this legacy video
	 */
	public void setDuration(String duration);

	/**
	 * Returns the host ID of this legacy video.
	 *
	 * @return the host ID of this legacy video
	 */
	public long getHostId();

	/**
	 * Sets the host ID of this legacy video.
	 *
	 * @param hostId the host ID of this legacy video
	 */
	public void setHostId(long hostId);

	/**
	 * Returns the text ID of this legacy video.
	 *
	 * @return the text ID of this legacy video
	 */
	public long getTextId();

	/**
	 * Sets the text ID of this legacy video.
	 *
	 * @param textId the text ID of this legacy video
	 */
	public void setTextId(long textId);

	/**
	 * Returns the file size of this legacy video.
	 *
	 * @return the file size of this legacy video
	 */
	@AutoEscape
	public String getFileSize();

	/**
	 * Sets the file size of this legacy video.
	 *
	 * @param fileSize the file size of this legacy video
	 */
	public void setFileSize(String fileSize);

	/**
	 * Returns the generation date of this legacy video.
	 *
	 * @return the generation date of this legacy video
	 */
	@AutoEscape
	public String getGenerationDate();

	/**
	 * Sets the generation date of this legacy video.
	 *
	 * @param generationDate the generation date of this legacy video
	 */
	public void setGenerationDate(String generationDate);

	/**
	 * Returns the open access of this legacy video.
	 *
	 * @return the open access of this legacy video
	 */
	public int getOpenAccess();

	/**
	 * Sets the open access of this legacy video.
	 *
	 * @param openAccess the open access of this legacy video
	 */
	public void setOpenAccess(int openAccess);

	/**
	 * Returns the download link of this legacy video.
	 *
	 * @return the download link of this legacy video
	 */
	public int getDownloadLink();

	/**
	 * Sets the download link of this legacy video.
	 *
	 * @param downloadLink the download link of this legacy video
	 */
	public void setDownloadLink(int downloadLink);

	/**
	 * Returns the metadata ID of this legacy video.
	 *
	 * @return the metadata ID of this legacy video
	 */
	public long getMetadataId();

	/**
	 * Sets the metadata ID of this legacy video.
	 *
	 * @param metadataId the metadata ID of this legacy video
	 */
	public void setMetadataId(long metadataId);

	/**
	 * Returns the surl of this legacy video.
	 *
	 * @return the surl of this legacy video
	 */
	@AutoEscape
	public String getSurl();

	/**
	 * Sets the surl of this legacy video.
	 *
	 * @param surl the surl of this legacy video
	 */
	public void setSurl(String surl);

	/**
	 * Returns the hits of this legacy video.
	 *
	 * @return the hits of this legacy video
	 */
	public long getHits();

	/**
	 * Sets the hits of this legacy video.
	 *
	 * @param hits the hits of this legacy video
	 */
	public void setHits(long hits);

	/**
	 * Returns the upload date of this legacy video.
	 *
	 * @return the upload date of this legacy video
	 */
	public Date getUploadDate();

	/**
	 * Sets the upload date of this legacy video.
	 *
	 * @param uploadDate the upload date of this legacy video
	 */
	public void setUploadDate(Date uploadDate);

	/**
	 * Returns the permitted to segment of this legacy video.
	 *
	 * @return the permitted to segment of this legacy video
	 */
	public int getPermittedToSegment();

	/**
	 * Sets the permitted to segment of this legacy video.
	 *
	 * @param permittedToSegment the permitted to segment of this legacy video
	 */
	public void setPermittedToSegment(int permittedToSegment);

	/**
	 * Returns the facility ID of this legacy video.
	 *
	 * @return the facility ID of this legacy video
	 */
	public long getFacilityId();

	/**
	 * Sets the facility ID of this legacy video.
	 *
	 * @param facilityId the facility ID of this legacy video
	 */
	public void setFacilityId(long facilityId);

	/**
	 * Returns the citation2go of this legacy video.
	 *
	 * @return the citation2go of this legacy video
	 */
	public int getCitation2go();

	/**
	 * Sets the citation2go of this legacy video.
	 *
	 * @param citation2go the citation2go of this legacy video
	 */
	public void setCitation2go(int citation2go);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.uhh.l2g.plugins.migration.model.LegacyVideo legacyVideo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.migration.model.LegacyVideo> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyVideo toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyVideo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}