/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LegacyVideoFacility service. Represents a row in the &quot;video_facility&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyVideoFacilityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyVideoFacilityImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyVideoFacility
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyVideoFacilityImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyVideoFacilityModelImpl
 * @generated
 */
public interface LegacyVideoFacilityModel extends BaseModel<LegacyVideoFacility> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy video facility model instance should use the {@link LegacyVideoFacility} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy video facility.
	 *
	 * @return the primary key of this legacy video facility
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacy video facility.
	 *
	 * @param primaryKey the primary key of this legacy video facility
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video facility ID of this legacy video facility.
	 *
	 * @return the video facility ID of this legacy video facility
	 */
	public long getVideoFacilityId();

	/**
	 * Sets the video facility ID of this legacy video facility.
	 *
	 * @param videoFacilityId the video facility ID of this legacy video facility
	 */
	public void setVideoFacilityId(long videoFacilityId);

	/**
	 * Returns the video ID of this legacy video facility.
	 *
	 * @return the video ID of this legacy video facility
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this legacy video facility.
	 *
	 * @param videoId the video ID of this legacy video facility
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the facility ID of this legacy video facility.
	 *
	 * @return the facility ID of this legacy video facility
	 */
	public long getFacilityId();

	/**
	 * Sets the facility ID of this legacy video facility.
	 *
	 * @param facilityId the facility ID of this legacy video facility
	 */
	public void setFacilityId(long facilityId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.uhh.l2g.plugins.migration.model.LegacyVideoFacility legacyVideoFacility);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.migration.model.LegacyVideoFacility> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyVideoFacility toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyVideoFacility toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}