/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LegacyUpload service. Represents a row in the &quot;upload&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyUploadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyUploadImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyUpload
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyUploadImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyUploadModelImpl
 * @generated
 */
public interface LegacyUploadModel extends BaseModel<LegacyUpload> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy upload model instance should use the {@link LegacyUpload} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy upload.
	 *
	 * @return the primary key of this legacy upload
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacy upload.
	 *
	 * @param primaryKey the primary key of this legacy upload
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this legacy upload.
	 *
	 * @return the ID of this legacy upload
	 */
	public long getId();

	/**
	 * Sets the ID of this legacy upload.
	 *
	 * @param id the ID of this legacy upload
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this legacy upload.
	 *
	 * @return the user ID of this legacy upload
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this legacy upload.
	 *
	 * @param userId the user ID of this legacy upload
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this legacy upload.
	 *
	 * @return the user uuid of this legacy upload
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this legacy upload.
	 *
	 * @param userUuid the user uuid of this legacy upload
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the content length of this legacy upload.
	 *
	 * @return the content length of this legacy upload
	 */
	public long getContentLength();

	/**
	 * Sets the content length of this legacy upload.
	 *
	 * @param contentLength the content length of this legacy upload
	 */
	public void setContentLength(long contentLength);

	/**
	 * Returns the timestamp of this legacy upload.
	 *
	 * @return the timestamp of this legacy upload
	 */
	public Date getTimestamp();

	/**
	 * Sets the timestamp of this legacy upload.
	 *
	 * @param timestamp the timestamp of this legacy upload
	 */
	public void setTimestamp(Date timestamp);

	/**
	 * Returns the status of this legacy upload.
	 *
	 * @return the status of this legacy upload
	 */
	public int getStatus();

	/**
	 * Sets the status of this legacy upload.
	 *
	 * @param status the status of this legacy upload
	 */
	public void setStatus(int status);

	/**
	 * Returns the video ID of this legacy upload.
	 *
	 * @return the video ID of this legacy upload
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this legacy upload.
	 *
	 * @param videoId the video ID of this legacy upload
	 */
	public void setVideoId(long videoId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LegacyUpload legacyUpload);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LegacyUpload> toCacheModel();

	@Override
	public LegacyUpload toEscapedModel();

	@Override
	public LegacyUpload toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}