/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LegacyMetadata service. Represents a row in the &quot;metadata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyMetadataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyMetadataImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyMetadata
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyMetadataImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyMetadataModelImpl
 * @generated
 */
public interface LegacyMetadataModel extends BaseModel<LegacyMetadata> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy metadata model instance should use the {@link LegacyMetadata} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy metadata.
	 *
	 * @return the primary key of this legacy metadata
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacy metadata.
	 *
	 * @param primaryKey the primary key of this legacy metadata
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this legacy metadata.
	 *
	 * @return the ID of this legacy metadata
	 */
	public long getId();

	/**
	 * Sets the ID of this legacy metadata.
	 *
	 * @param id the ID of this legacy metadata
	 */
	public void setId(long id);

	/**
	 * Returns the u r l i d of this legacy metadata.
	 *
	 * @return the u r l i d of this legacy metadata
	 */
	@AutoEscape
	public String getURLID();

	/**
	 * Sets the u r l i d of this legacy metadata.
	 *
	 * @param URLID the u r l i d of this legacy metadata
	 */
	public void setURLID(String URLID);

	/**
	 * Returns the format of this legacy metadata.
	 *
	 * @return the format of this legacy metadata
	 */
	@AutoEscape
	public String getFormat();

	/**
	 * Sets the format of this legacy metadata.
	 *
	 * @param format the format of this legacy metadata
	 */
	public void setFormat(String format);

	/**
	 * Returns the type of this legacy metadata.
	 *
	 * @return the type of this legacy metadata
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this legacy metadata.
	 *
	 * @param type the type of this legacy metadata
	 */
	public void setType(String type);

	/**
	 * Returns the language of this legacy metadata.
	 *
	 * @return the language of this legacy metadata
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this legacy metadata.
	 *
	 * @param language the language of this legacy metadata
	 */
	public void setLanguage(String language);

	/**
	 * Returns the title of this legacy metadata.
	 *
	 * @return the title of this legacy metadata
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this legacy metadata.
	 *
	 * @param title the title of this legacy metadata
	 */
	public void setTitle(String title);

	/**
	 * Returns the subject of this legacy metadata.
	 *
	 * @return the subject of this legacy metadata
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this legacy metadata.
	 *
	 * @param subject the subject of this legacy metadata
	 */
	public void setSubject(String subject);

	/**
	 * Returns the coverage of this legacy metadata.
	 *
	 * @return the coverage of this legacy metadata
	 */
	@AutoEscape
	public String getCoverage();

	/**
	 * Sets the coverage of this legacy metadata.
	 *
	 * @param coverage the coverage of this legacy metadata
	 */
	public void setCoverage(String coverage);

	/**
	 * Returns the description of this legacy metadata.
	 *
	 * @return the description of this legacy metadata
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this legacy metadata.
	 *
	 * @param description the description of this legacy metadata
	 */
	public void setDescription(String description);

	/**
	 * Returns the creator of this legacy metadata.
	 *
	 * @return the creator of this legacy metadata
	 */
	@AutoEscape
	public String getCreator();

	/**
	 * Sets the creator of this legacy metadata.
	 *
	 * @param creator the creator of this legacy metadata
	 */
	public void setCreator(String creator);

	/**
	 * Returns the publisher of this legacy metadata.
	 *
	 * @return the publisher of this legacy metadata
	 */
	@AutoEscape
	public String getPublisher();

	/**
	 * Sets the publisher of this legacy metadata.
	 *
	 * @param publisher the publisher of this legacy metadata
	 */
	public void setPublisher(String publisher);

	/**
	 * Returns the contributor of this legacy metadata.
	 *
	 * @return the contributor of this legacy metadata
	 */
	@AutoEscape
	public String getContributor();

	/**
	 * Sets the contributor of this legacy metadata.
	 *
	 * @param contributor the contributor of this legacy metadata
	 */
	public void setContributor(String contributor);

	/**
	 * Returns the rights holder of this legacy metadata.
	 *
	 * @return the rights holder of this legacy metadata
	 */
	@AutoEscape
	public String getRightsHolder();

	/**
	 * Sets the rights holder of this legacy metadata.
	 *
	 * @param rightsHolder the rights holder of this legacy metadata
	 */
	public void setRightsHolder(String rightsHolder);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LegacyMetadata legacyMetadata);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LegacyMetadata> toCacheModel();

	@Override
	public LegacyMetadata toEscapedModel();

	@Override
	public LegacyMetadata toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}