/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LegacyLectureSeries service. Represents a row in the &quot;lectureseries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyLectureSeriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyLectureSeriesImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyLectureSeries
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyLectureSeriesImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyLectureSeriesModelImpl
 * @generated
 */
public interface LegacyLectureSeriesModel extends BaseModel<LegacyLectureSeries> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy lecture series model instance should use the {@link LegacyLectureSeries} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy lecture series.
	 *
	 * @return the primary key of this legacy lecture series
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacy lecture series.
	 *
	 * @param primaryKey the primary key of this legacy lecture series
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the number of this legacy lecture series.
	 *
	 * @return the number of this legacy lecture series
	 */
	@AutoEscape
	public String getNumber();

	/**
	 * Sets the number of this legacy lecture series.
	 *
	 * @param number the number of this legacy lecture series
	 */
	public void setNumber(String number);

	/**
	 * Returns the event type of this legacy lecture series.
	 *
	 * @return the event type of this legacy lecture series
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this legacy lecture series.
	 *
	 * @param eventType the event type of this legacy lecture series
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the event category of this legacy lecture series.
	 *
	 * @return the event category of this legacy lecture series
	 */
	@AutoEscape
	public String getEventCategory();

	/**
	 * Sets the event category of this legacy lecture series.
	 *
	 * @param eventCategory the event category of this legacy lecture series
	 */
	public void setEventCategory(String eventCategory);

	/**
	 * Returns the name of this legacy lecture series.
	 *
	 * @return the name of this legacy lecture series
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this legacy lecture series.
	 *
	 * @param name the name of this legacy lecture series
	 */
	public void setName(String name);

	/**
	 * Returns the short desc of this legacy lecture series.
	 *
	 * @return the short desc of this legacy lecture series
	 */
	@AutoEscape
	public String getShortDesc();

	/**
	 * Sets the short desc of this legacy lecture series.
	 *
	 * @param shortDesc the short desc of this legacy lecture series
	 */
	public void setShortDesc(String shortDesc);

	/**
	 * Returns the semester name of this legacy lecture series.
	 *
	 * @return the semester name of this legacy lecture series
	 */
	@AutoEscape
	public String getSemesterName();

	/**
	 * Sets the semester name of this legacy lecture series.
	 *
	 * @param semesterName the semester name of this legacy lecture series
	 */
	public void setSemesterName(String semesterName);

	/**
	 * Returns the language of this legacy lecture series.
	 *
	 * @return the language of this legacy lecture series
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this legacy lecture series.
	 *
	 * @param language the language of this legacy lecture series
	 */
	public void setLanguage(String language);

	/**
	 * Returns the faculty name of this legacy lecture series.
	 *
	 * @return the faculty name of this legacy lecture series
	 */
	@AutoEscape
	public String getFacultyName();

	/**
	 * Sets the faculty name of this legacy lecture series.
	 *
	 * @param facultyName the faculty name of this legacy lecture series
	 */
	public void setFacultyName(String facultyName);

	/**
	 * Returns the instructors string of this legacy lecture series.
	 *
	 * @return the instructors string of this legacy lecture series
	 */
	@AutoEscape
	public String getInstructorsString();

	/**
	 * Sets the instructors string of this legacy lecture series.
	 *
	 * @param instructorsString the instructors string of this legacy lecture series
	 */
	public void setInstructorsString(String instructorsString);

	/**
	 * Returns the ID of this legacy lecture series.
	 *
	 * @return the ID of this legacy lecture series
	 */
	public long getId();

	/**
	 * Sets the ID of this legacy lecture series.
	 *
	 * @param id the ID of this legacy lecture series
	 */
	public void setId(long id);

	/**
	 * Returns the password of this legacy lecture series.
	 *
	 * @return the password of this legacy lecture series
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this legacy lecture series.
	 *
	 * @param password the password of this legacy lecture series
	 */
	public void setPassword(String password);

	/**
	 * Returns the approved of this legacy lecture series.
	 *
	 * @return the approved of this legacy lecture series
	 */
	public int getApproved();

	/**
	 * Sets the approved of this legacy lecture series.
	 *
	 * @param approved the approved of this legacy lecture series
	 */
	public void setApproved(int approved);

	/**
	 * Returns the long desc of this legacy lecture series.
	 *
	 * @return the long desc of this legacy lecture series
	 */
	@AutoEscape
	public String getLongDesc();

	/**
	 * Sets the long desc of this legacy lecture series.
	 *
	 * @param longDesc the long desc of this legacy lecture series
	 */
	public void setLongDesc(String longDesc);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LegacyLectureSeries legacyLectureSeries);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LegacyLectureSeries> toCacheModel();

	@Override
	public LegacyLectureSeries toEscapedModel();

	@Override
	public LegacyLectureSeries toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}