/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LegacyAddress service. Represents a row in the &quot;Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyAddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyAddressImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyAddress
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyAddressImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyAddressModelImpl
 * @generated
 */
public interface LegacyAddressModel extends AttachedModel, AuditedModel,
	BaseModel<LegacyAddress> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy address model instance should use the {@link LegacyAddress} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy address.
	 *
	 * @return the primary key of this legacy address
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacy address.
	 *
	 * @param primaryKey the primary key of this legacy address
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the address ID of this legacy address.
	 *
	 * @return the address ID of this legacy address
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this legacy address.
	 *
	 * @param addressId the address ID of this legacy address
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the company ID of this legacy address.
	 *
	 * @return the company ID of this legacy address
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this legacy address.
	 *
	 * @param companyId the company ID of this legacy address
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this legacy address.
	 *
	 * @return the user ID of this legacy address
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this legacy address.
	 *
	 * @param userId the user ID of this legacy address
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this legacy address.
	 *
	 * @return the user uuid of this legacy address
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this legacy address.
	 *
	 * @param userUuid the user uuid of this legacy address
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this legacy address.
	 *
	 * @return the user name of this legacy address
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this legacy address.
	 *
	 * @param userName the user name of this legacy address
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this legacy address.
	 *
	 * @return the create date of this legacy address
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this legacy address.
	 *
	 * @param createDate the create date of this legacy address
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this legacy address.
	 *
	 * @return the modified date of this legacy address
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this legacy address.
	 *
	 * @param modifiedDate the modified date of this legacy address
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this legacy address.
	 *
	 * @return the fully qualified class name of this legacy address
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this legacy address.
	 *
	 * @return the class name ID of this legacy address
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this legacy address.
	 *
	 * @param classNameId the class name ID of this legacy address
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this legacy address.
	 *
	 * @return the class p k of this legacy address
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this legacy address.
	 *
	 * @param classPK the class p k of this legacy address
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the street1 of this legacy address.
	 *
	 * @return the street1 of this legacy address
	 */
	@AutoEscape
	public String getStreet1();

	/**
	 * Sets the street1 of this legacy address.
	 *
	 * @param street1 the street1 of this legacy address
	 */
	public void setStreet1(String street1);

	/**
	 * Returns the street2 of this legacy address.
	 *
	 * @return the street2 of this legacy address
	 */
	@AutoEscape
	public String getStreet2();

	/**
	 * Sets the street2 of this legacy address.
	 *
	 * @param street2 the street2 of this legacy address
	 */
	public void setStreet2(String street2);

	/**
	 * Returns the street3 of this legacy address.
	 *
	 * @return the street3 of this legacy address
	 */
	@AutoEscape
	public String getStreet3();

	/**
	 * Sets the street3 of this legacy address.
	 *
	 * @param street3 the street3 of this legacy address
	 */
	public void setStreet3(String street3);

	/**
	 * Returns the city of this legacy address.
	 *
	 * @return the city of this legacy address
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this legacy address.
	 *
	 * @param city the city of this legacy address
	 */
	public void setCity(String city);

	/**
	 * Returns the zip of this legacy address.
	 *
	 * @return the zip of this legacy address
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this legacy address.
	 *
	 * @param zip the zip of this legacy address
	 */
	public void setZip(String zip);

	/**
	 * Returns the region ID of this legacy address.
	 *
	 * @return the region ID of this legacy address
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this legacy address.
	 *
	 * @param regionId the region ID of this legacy address
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the country ID of this legacy address.
	 *
	 * @return the country ID of this legacy address
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this legacy address.
	 *
	 * @param countryId the country ID of this legacy address
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the type ID of this legacy address.
	 *
	 * @return the type ID of this legacy address
	 */
	public int getTypeId();

	/**
	 * Sets the type ID of this legacy address.
	 *
	 * @param typeId the type ID of this legacy address
	 */
	public void setTypeId(int typeId);

	/**
	 * Returns the mailing of this legacy address.
	 *
	 * @return the mailing of this legacy address
	 */
	public boolean getMailing();

	/**
	 * Returns <code>true</code> if this legacy address is mailing.
	 *
	 * @return <code>true</code> if this legacy address is mailing; <code>false</code> otherwise
	 */
	public boolean isMailing();

	/**
	 * Sets whether this legacy address is mailing.
	 *
	 * @param mailing the mailing of this legacy address
	 */
	public void setMailing(boolean mailing);

	/**
	 * Returns the primary of this legacy address.
	 *
	 * @return the primary of this legacy address
	 */
	public boolean getPrimary();

	/**
	 * Returns <code>true</code> if this legacy address is primary.
	 *
	 * @return <code>true</code> if this legacy address is primary; <code>false</code> otherwise
	 */
	public boolean isPrimary();

	/**
	 * Sets whether this legacy address is primary.
	 *
	 * @param primary the primary of this legacy address
	 */
	public void setPrimary(boolean primary);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.uhh.l2g.plugins.migration.model.LegacyAddress legacyAddress);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.migration.model.LegacyAddress> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyAddress toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyAddress toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}