/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LegacySegment service. Represents a row in the &quot;segment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacySegmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacySegmentImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacySegment
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacySegmentImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacySegmentModelImpl
 * @generated
 */
public interface LegacySegmentModel extends BaseModel<LegacySegment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy segment model instance should use the {@link LegacySegment} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy segment.
	 *
	 * @return the primary key of this legacy segment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacy segment.
	 *
	 * @param primaryKey the primary key of this legacy segment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this legacy segment.
	 *
	 * @return the ID of this legacy segment
	 */
	public long getId();

	/**
	 * Sets the ID of this legacy segment.
	 *
	 * @param id the ID of this legacy segment
	 */
	public void setId(long id);

	/**
	 * Returns the video ID of this legacy segment.
	 *
	 * @return the video ID of this legacy segment
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this legacy segment.
	 *
	 * @param videoId the video ID of this legacy segment
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the start of this legacy segment.
	 *
	 * @return the start of this legacy segment
	 */
	@AutoEscape
	public String getStart();

	/**
	 * Sets the start of this legacy segment.
	 *
	 * @param start the start of this legacy segment
	 */
	public void setStart(String start);

	/**
	 * Returns the title of this legacy segment.
	 *
	 * @return the title of this legacy segment
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this legacy segment.
	 *
	 * @param title the title of this legacy segment
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this legacy segment.
	 *
	 * @return the description of this legacy segment
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this legacy segment.
	 *
	 * @param description the description of this legacy segment
	 */
	public void setDescription(String description);

	/**
	 * Returns the end of this legacy segment.
	 *
	 * @return the end of this legacy segment
	 */
	@AutoEscape
	public String getEnd();

	/**
	 * Sets the end of this legacy segment.
	 *
	 * @param end the end of this legacy segment
	 */
	public void setEnd(String end);

	/**
	 * Returns the chapter of this legacy segment.
	 *
	 * @return the chapter of this legacy segment
	 */
	public int getChapter();

	/**
	 * Sets the chapter of this legacy segment.
	 *
	 * @param chapter the chapter of this legacy segment
	 */
	public void setChapter(int chapter);

	/**
	 * Returns the user ID of this legacy segment.
	 *
	 * @return the user ID of this legacy segment
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this legacy segment.
	 *
	 * @param userId the user ID of this legacy segment
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this legacy segment.
	 *
	 * @return the user uuid of this legacy segment
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this legacy segment.
	 *
	 * @param userUuid the user uuid of this legacy segment
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.uhh.l2g.plugins.migration.model.LegacySegment legacySegment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.migration.model.LegacySegment> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacySegment toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacySegment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}