/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LegacyContact service. Represents a row in the &quot;Contact_&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyContactImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyContact
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyContactImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyContactModelImpl
 * @generated
 */
public interface LegacyContactModel extends AuditedModel,
	BaseModel<LegacyContact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy contact model instance should use the {@link LegacyContact} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy contact.
	 *
	 * @return the primary key of this legacy contact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacy contact.
	 *
	 * @param primaryKey the primary key of this legacy contact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the contact ID of this legacy contact.
	 *
	 * @return the contact ID of this legacy contact
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this legacy contact.
	 *
	 * @param contactId the contact ID of this legacy contact
	 */
	public void setContactId(long contactId);

	/**
	 * Returns the company ID of this legacy contact.
	 *
	 * @return the company ID of this legacy contact
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this legacy contact.
	 *
	 * @param companyId the company ID of this legacy contact
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this legacy contact.
	 *
	 * @return the user ID of this legacy contact
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this legacy contact.
	 *
	 * @param userId the user ID of this legacy contact
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this legacy contact.
	 *
	 * @return the user uuid of this legacy contact
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this legacy contact.
	 *
	 * @param userUuid the user uuid of this legacy contact
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this legacy contact.
	 *
	 * @return the user name of this legacy contact
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this legacy contact.
	 *
	 * @param userName the user name of this legacy contact
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this legacy contact.
	 *
	 * @return the create date of this legacy contact
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this legacy contact.
	 *
	 * @param createDate the create date of this legacy contact
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this legacy contact.
	 *
	 * @return the modified date of this legacy contact
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this legacy contact.
	 *
	 * @param modifiedDate the modified date of this legacy contact
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the account ID of this legacy contact.
	 *
	 * @return the account ID of this legacy contact
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this legacy contact.
	 *
	 * @param accountId the account ID of this legacy contact
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the parent contact ID of this legacy contact.
	 *
	 * @return the parent contact ID of this legacy contact
	 */
	public long getParentContactId();

	/**
	 * Sets the parent contact ID of this legacy contact.
	 *
	 * @param parentContactId the parent contact ID of this legacy contact
	 */
	public void setParentContactId(long parentContactId);

	/**
	 * Returns the first name of this legacy contact.
	 *
	 * @return the first name of this legacy contact
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this legacy contact.
	 *
	 * @param firstName the first name of this legacy contact
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this legacy contact.
	 *
	 * @return the middle name of this legacy contact
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this legacy contact.
	 *
	 * @param middleName the middle name of this legacy contact
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this legacy contact.
	 *
	 * @return the last name of this legacy contact
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this legacy contact.
	 *
	 * @param lastName the last name of this legacy contact
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the prefix ID of this legacy contact.
	 *
	 * @return the prefix ID of this legacy contact
	 */
	public int getPrefixId();

	/**
	 * Sets the prefix ID of this legacy contact.
	 *
	 * @param prefixId the prefix ID of this legacy contact
	 */
	public void setPrefixId(int prefixId);

	/**
	 * Returns the suffix ID of this legacy contact.
	 *
	 * @return the suffix ID of this legacy contact
	 */
	public int getSuffixId();

	/**
	 * Sets the suffix ID of this legacy contact.
	 *
	 * @param suffixId the suffix ID of this legacy contact
	 */
	public void setSuffixId(int suffixId);

	/**
	 * Returns the male of this legacy contact.
	 *
	 * @return the male of this legacy contact
	 */
	public boolean getMale();

	/**
	 * Returns <code>true</code> if this legacy contact is male.
	 *
	 * @return <code>true</code> if this legacy contact is male; <code>false</code> otherwise
	 */
	public boolean isMale();

	/**
	 * Sets whether this legacy contact is male.
	 *
	 * @param male the male of this legacy contact
	 */
	public void setMale(boolean male);

	/**
	 * Returns the birthday of this legacy contact.
	 *
	 * @return the birthday of this legacy contact
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this legacy contact.
	 *
	 * @param birthday the birthday of this legacy contact
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the sms sn of this legacy contact.
	 *
	 * @return the sms sn of this legacy contact
	 */
	@AutoEscape
	public String getSmsSn();

	/**
	 * Sets the sms sn of this legacy contact.
	 *
	 * @param smsSn the sms sn of this legacy contact
	 */
	public void setSmsSn(String smsSn);

	/**
	 * Returns the aim sn of this legacy contact.
	 *
	 * @return the aim sn of this legacy contact
	 */
	@AutoEscape
	public String getAimSn();

	/**
	 * Sets the aim sn of this legacy contact.
	 *
	 * @param aimSn the aim sn of this legacy contact
	 */
	public void setAimSn(String aimSn);

	/**
	 * Returns the facebook sn of this legacy contact.
	 *
	 * @return the facebook sn of this legacy contact
	 */
	@AutoEscape
	public String getFacebookSn();

	/**
	 * Sets the facebook sn of this legacy contact.
	 *
	 * @param facebookSn the facebook sn of this legacy contact
	 */
	public void setFacebookSn(String facebookSn);

	/**
	 * Returns the icq sn of this legacy contact.
	 *
	 * @return the icq sn of this legacy contact
	 */
	@AutoEscape
	public String getIcqSn();

	/**
	 * Sets the icq sn of this legacy contact.
	 *
	 * @param icqSn the icq sn of this legacy contact
	 */
	public void setIcqSn(String icqSn);

	/**
	 * Returns the jabber sn of this legacy contact.
	 *
	 * @return the jabber sn of this legacy contact
	 */
	@AutoEscape
	public String getJabberSn();

	/**
	 * Sets the jabber sn of this legacy contact.
	 *
	 * @param jabberSn the jabber sn of this legacy contact
	 */
	public void setJabberSn(String jabberSn);

	/**
	 * Returns the msn sn of this legacy contact.
	 *
	 * @return the msn sn of this legacy contact
	 */
	@AutoEscape
	public String getMsnSn();

	/**
	 * Sets the msn sn of this legacy contact.
	 *
	 * @param msnSn the msn sn of this legacy contact
	 */
	public void setMsnSn(String msnSn);

	/**
	 * Returns the my space sn of this legacy contact.
	 *
	 * @return the my space sn of this legacy contact
	 */
	@AutoEscape
	public String getMySpaceSn();

	/**
	 * Sets the my space sn of this legacy contact.
	 *
	 * @param mySpaceSn the my space sn of this legacy contact
	 */
	public void setMySpaceSn(String mySpaceSn);

	/**
	 * Returns the skype sn of this legacy contact.
	 *
	 * @return the skype sn of this legacy contact
	 */
	@AutoEscape
	public String getSkypeSn();

	/**
	 * Sets the skype sn of this legacy contact.
	 *
	 * @param skypeSn the skype sn of this legacy contact
	 */
	public void setSkypeSn(String skypeSn);

	/**
	 * Returns the twitter sn of this legacy contact.
	 *
	 * @return the twitter sn of this legacy contact
	 */
	@AutoEscape
	public String getTwitterSn();

	/**
	 * Sets the twitter sn of this legacy contact.
	 *
	 * @param twitterSn the twitter sn of this legacy contact
	 */
	public void setTwitterSn(String twitterSn);

	/**
	 * Returns the ym sn of this legacy contact.
	 *
	 * @return the ym sn of this legacy contact
	 */
	@AutoEscape
	public String getYmSn();

	/**
	 * Sets the ym sn of this legacy contact.
	 *
	 * @param ymSn the ym sn of this legacy contact
	 */
	public void setYmSn(String ymSn);

	/**
	 * Returns the employee status ID of this legacy contact.
	 *
	 * @return the employee status ID of this legacy contact
	 */
	@AutoEscape
	public String getEmployeeStatusId();

	/**
	 * Sets the employee status ID of this legacy contact.
	 *
	 * @param employeeStatusId the employee status ID of this legacy contact
	 */
	public void setEmployeeStatusId(String employeeStatusId);

	/**
	 * Returns the employee number of this legacy contact.
	 *
	 * @return the employee number of this legacy contact
	 */
	@AutoEscape
	public String getEmployeeNumber();

	/**
	 * Sets the employee number of this legacy contact.
	 *
	 * @param employeeNumber the employee number of this legacy contact
	 */
	public void setEmployeeNumber(String employeeNumber);

	/**
	 * Returns the job title of this legacy contact.
	 *
	 * @return the job title of this legacy contact
	 */
	@AutoEscape
	public String getJobTitle();

	/**
	 * Sets the job title of this legacy contact.
	 *
	 * @param jobTitle the job title of this legacy contact
	 */
	public void setJobTitle(String jobTitle);

	/**
	 * Returns the job class of this legacy contact.
	 *
	 * @return the job class of this legacy contact
	 */
	@AutoEscape
	public String getJobClass();

	/**
	 * Sets the job class of this legacy contact.
	 *
	 * @param jobClass the job class of this legacy contact
	 */
	public void setJobClass(String jobClass);

	/**
	 * Returns the hours of operation of this legacy contact.
	 *
	 * @return the hours of operation of this legacy contact
	 */
	@AutoEscape
	public String getHoursOfOperation();

	/**
	 * Sets the hours of operation of this legacy contact.
	 *
	 * @param hoursOfOperation the hours of operation of this legacy contact
	 */
	public void setHoursOfOperation(String hoursOfOperation);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.uhh.l2g.plugins.migration.model.LegacyContact legacyContact);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.migration.model.LegacyContact> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyContact toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.LegacyContact toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}