/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LegacyOffice service. Represents a row in the &quot;office&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.LegacyOfficeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.LegacyOfficeImpl}.
 * </p>
 *
 * @author unihh
 * @see LegacyOffice
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyOfficeImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.LegacyOfficeModelImpl
 * @generated
 */
public interface LegacyOfficeModel extends BaseModel<LegacyOffice> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legacy office model instance should use the {@link LegacyOffice} interface instead.
	 */

	/**
	 * Returns the primary key of this legacy office.
	 *
	 * @return the primary key of this legacy office
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this legacy office.
	 *
	 * @param primaryKey the primary key of this legacy office
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this legacy office.
	 *
	 * @return the ID of this legacy office
	 */
	public long getId();

	/**
	 * Sets the ID of this legacy office.
	 *
	 * @param id the ID of this legacy office
	 */
	public void setId(long id);

	/**
	 * Returns the name of this legacy office.
	 *
	 * @return the name of this legacy office
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this legacy office.
	 *
	 * @param name the name of this legacy office
	 */
	public void setName(String name);

	/**
	 * Returns the www of this legacy office.
	 *
	 * @return the www of this legacy office
	 */
	@AutoEscape
	public String getWww();

	/**
	 * Sets the www of this legacy office.
	 *
	 * @param www the www of this legacy office
	 */
	public void setWww(String www);

	/**
	 * Returns the email of this legacy office.
	 *
	 * @return the email of this legacy office
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this legacy office.
	 *
	 * @param email the email of this legacy office
	 */
	public void setEmail(String email);

	/**
	 * Returns the facility ID of this legacy office.
	 *
	 * @return the facility ID of this legacy office
	 */
	public long getFacilityId();

	/**
	 * Sets the facility ID of this legacy office.
	 *
	 * @param facilityId the facility ID of this legacy office
	 */
	public void setFacilityId(long facilityId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LegacyOffice legacyOffice);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LegacyOffice> toCacheModel();

	@Override
	public LegacyOffice toEscapedModel();

	@Override
	public LegacyOffice toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}