/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TestEntityTwo service. Represents a row in the &quot;LG_Migration_TestEntityTwo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.migration.model.impl.TestEntityTwoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.migration.model.impl.TestEntityTwoImpl}.
 * </p>
 *
 * @author unihh
 * @see TestEntityTwo
 * @see de.uhh.l2g.plugins.migration.model.impl.TestEntityTwoImpl
 * @see de.uhh.l2g.plugins.migration.model.impl.TestEntityTwoModelImpl
 * @generated
 */
public interface TestEntityTwoModel extends BaseModel<TestEntityTwo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test entity two model instance should use the {@link TestEntityTwo} interface instead.
	 */

	/**
	 * Returns the primary key of this test entity two.
	 *
	 * @return the primary key of this test entity two
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test entity two.
	 *
	 * @param primaryKey the primary key of this test entity two
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the plid of this test entity two.
	 *
	 * @return the plid of this test entity two
	 */
	public long getPlid();

	/**
	 * Sets the plid of this test entity two.
	 *
	 * @param plid the plid of this test entity two
	 */
	public void setPlid(long plid);

	/**
	 * Returns the group ID of this test entity two.
	 *
	 * @return the group ID of this test entity two
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this test entity two.
	 *
	 * @param groupId the group ID of this test entity two
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this test entity two.
	 *
	 * @return the company ID of this test entity two
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this test entity two.
	 *
	 * @param companyId the company ID of this test entity two
	 */
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.uhh.l2g.plugins.migration.model.TestEntityTwo testEntityTwo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.migration.model.TestEntityTwo> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.TestEntityTwo toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.migration.model.TestEntityTwo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}