/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Autocomplete service. Represents a row in the &quot;LG_Autocomplete&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.AutocompleteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.AutocompleteImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Autocomplete
 * @see de.uhh.l2g.plugins.model.impl.AutocompleteImpl
 * @see de.uhh.l2g.plugins.model.impl.AutocompleteModelImpl
 * @generated
 */
public interface AutocompleteModel extends BaseModel<Autocomplete> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a autocomplete model instance should use the {@link Autocomplete} interface instead.
	 */

	/**
	 * Returns the primary key of this autocomplete.
	 *
	 * @return the primary key of this autocomplete
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this autocomplete.
	 *
	 * @param primaryKey the primary key of this autocomplete
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the autocomplete ID of this autocomplete.
	 *
	 * @return the autocomplete ID of this autocomplete
	 */
	public long getAutocompleteId();

	/**
	 * Sets the autocomplete ID of this autocomplete.
	 *
	 * @param autocompleteId the autocomplete ID of this autocomplete
	 */
	public void setAutocompleteId(long autocompleteId);

	/**
	 * Returns the search words json of this autocomplete.
	 *
	 * @return the search words json of this autocomplete
	 */
	@AutoEscape
	public String getSearchWordsJson();

	/**
	 * Sets the search words json of this autocomplete.
	 *
	 * @param searchWordsJson the search words json of this autocomplete
	 */
	public void setSearchWordsJson(String searchWordsJson);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.uhh.l2g.plugins.model.Autocomplete autocomplete);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.model.Autocomplete> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.model.Autocomplete toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.model.Autocomplete toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}