/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the InstallWizard service. Represents a row in the &quot;LG_InstallWizard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.InstallWizardModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.InstallWizardImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see InstallWizard
 * @see de.uhh.l2g.plugins.model.impl.InstallWizardImpl
 * @see de.uhh.l2g.plugins.model.impl.InstallWizardModelImpl
 * @generated
 */
public interface InstallWizardModel extends BaseModel<InstallWizard> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a install wizard model instance should use the {@link InstallWizard} interface instead.
	 */

	/**
	 * Returns the primary key of this install wizard.
	 *
	 * @return the primary key of this install wizard
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this install wizard.
	 *
	 * @param primaryKey the primary key of this install wizard
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the install wizard ID of this install wizard.
	 *
	 * @return the install wizard ID of this install wizard
	 */
	public long getInstallWizardId();

	/**
	 * Sets the install wizard ID of this install wizard.
	 *
	 * @param installWizardId the install wizard ID of this install wizard
	 */
	public void setInstallWizardId(long installWizardId);

	/**
	 * Returns the wizart active of this install wizard.
	 *
	 * @return the wizart active of this install wizard
	 */
	public int getWizartActive();

	/**
	 * Sets the wizart active of this install wizard.
	 *
	 * @param wizartActive the wizart active of this install wizard
	 */
	public void setWizartActive(int wizartActive);

	/**
	 * Returns the group ID of this install wizard.
	 *
	 * @return the group ID of this install wizard
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this install wizard.
	 *
	 * @param groupId the group ID of this install wizard
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this install wizard.
	 *
	 * @return the company ID of this install wizard
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this install wizard.
	 *
	 * @param companyId the company ID of this install wizard
	 */
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.uhh.l2g.plugins.model.InstallWizard installWizard);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.model.InstallWizard> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.model.InstallWizard toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.model.InstallWizard toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}