/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Office service. Represents a row in the &quot;LG_Office&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.OfficeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.OfficeImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Office
 * @see de.uhh.l2g.plugins.model.impl.OfficeImpl
 * @see de.uhh.l2g.plugins.model.impl.OfficeModelImpl
 * @generated
 */
public interface OfficeModel extends BaseModel<Office> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a office model instance should use the {@link Office} interface instead.
	 */

	/**
	 * Returns the primary key of this office.
	 *
	 * @return the primary key of this office
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this office.
	 *
	 * @param primaryKey the primary key of this office
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the office ID of this office.
	 *
	 * @return the office ID of this office
	 */
	public long getOfficeId();

	/**
	 * Sets the office ID of this office.
	 *
	 * @param officeId the office ID of this office
	 */
	public void setOfficeId(long officeId);

	/**
	 * Returns the name of this office.
	 *
	 * @return the name of this office
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this office.
	 *
	 * @param name the name of this office
	 */
	public void setName(String name);

	/**
	 * Returns the www of this office.
	 *
	 * @return the www of this office
	 */
	@AutoEscape
	public String getWww();

	/**
	 * Sets the www of this office.
	 *
	 * @param www the www of this office
	 */
	public void setWww(String www);

	/**
	 * Returns the email of this office.
	 *
	 * @return the email of this office
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this office.
	 *
	 * @param email the email of this office
	 */
	public void setEmail(String email);

	/**
	 * Returns the institution ID of this office.
	 *
	 * @return the institution ID of this office
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this office.
	 *
	 * @param institutionId the institution ID of this office
	 */
	public void setInstitutionId(long institutionId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.uhh.l2g.plugins.model.Office office);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.model.Office> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.model.Office toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.model.Office toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}