/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ScheduledThread service. Represents a row in the &quot;LG_ScheduledThread&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.ScheduledThreadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.ScheduledThreadImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see ScheduledThread
 * @see de.uhh.l2g.plugins.model.impl.ScheduledThreadImpl
 * @see de.uhh.l2g.plugins.model.impl.ScheduledThreadModelImpl
 * @generated
 */
public interface ScheduledThreadModel extends BaseModel<ScheduledThread>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a scheduled thread model instance should use the {@link ScheduledThread} interface instead.
	 */

	/**
	 * Returns the primary key of this scheduled thread.
	 *
	 * @return the primary key of this scheduled thread
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this scheduled thread.
	 *
	 * @param primaryKey the primary key of this scheduled thread
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the scheduled thread ID of this scheduled thread.
	 *
	 * @return the scheduled thread ID of this scheduled thread
	 */
	public long getScheduledThreadId();

	/**
	 * Sets the scheduled thread ID of this scheduled thread.
	 *
	 * @param scheduledThreadId the scheduled thread ID of this scheduled thread
	 */
	public void setScheduledThreadId(long scheduledThreadId);

	/**
	 * Returns the group ID of this scheduled thread.
	 *
	 * @return the group ID of this scheduled thread
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this scheduled thread.
	 *
	 * @param groupId the group ID of this scheduled thread
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this scheduled thread.
	 *
	 * @return the company ID of this scheduled thread
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this scheduled thread.
	 *
	 * @param companyId the company ID of this scheduled thread
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this scheduled thread.
	 *
	 * @return the user ID of this scheduled thread
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this scheduled thread.
	 *
	 * @param userId the user ID of this scheduled thread
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this scheduled thread.
	 *
	 * @return the user uuid of this scheduled thread
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this scheduled thread.
	 *
	 * @param userUuid the user uuid of this scheduled thread
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this scheduled thread.
	 *
	 * @return the user name of this scheduled thread
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this scheduled thread.
	 *
	 * @param userName the user name of this scheduled thread
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this scheduled thread.
	 *
	 * @return the create date of this scheduled thread
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this scheduled thread.
	 *
	 * @param createDate the create date of this scheduled thread
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this scheduled thread.
	 *
	 * @return the modified date of this scheduled thread
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this scheduled thread.
	 *
	 * @param modifiedDate the modified date of this scheduled thread
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the scheduler class name of this scheduled thread.
	 *
	 * @return the scheduler class name of this scheduled thread
	 */
	@AutoEscape
	public String getSchedulerClassName();

	/**
	 * Sets the scheduler class name of this scheduled thread.
	 *
	 * @param schedulerClassName the scheduler class name of this scheduled thread
	 */
	public void setSchedulerClassName(String schedulerClassName);

	/**
	 * Returns the cron text of this scheduled thread.
	 *
	 * @return the cron text of this scheduled thread
	 */
	@AutoEscape
	public String getCronText();

	/**
	 * Sets the cron text of this scheduled thread.
	 *
	 * @param cronText the cron text of this scheduled thread
	 */
	public void setCronText(String cronText);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.uhh.l2g.plugins.model.ScheduledThread scheduledThread);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.model.ScheduledThread> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.model.ScheduledThread toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.model.ScheduledThread toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}