/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Segment_User_Video service. Represents a row in the &quot;LG_Segment_User_Video&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.Segment_User_VideoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.Segment_User_VideoImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Segment_User_Video
 * @see de.uhh.l2g.plugins.model.impl.Segment_User_VideoImpl
 * @see de.uhh.l2g.plugins.model.impl.Segment_User_VideoModelImpl
 * @generated
 */
public interface Segment_User_VideoModel extends BaseModel<Segment_User_Video> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a segment_ user_ video model instance should use the {@link Segment_User_Video} interface instead.
	 */

	/**
	 * Returns the primary key of this segment_ user_ video.
	 *
	 * @return the primary key of this segment_ user_ video
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this segment_ user_ video.
	 *
	 * @param primaryKey the primary key of this segment_ user_ video
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the segment ID of this segment_ user_ video.
	 *
	 * @return the segment ID of this segment_ user_ video
	 */
	public long getSegmentId();

	/**
	 * Sets the segment ID of this segment_ user_ video.
	 *
	 * @param segmentId the segment ID of this segment_ user_ video
	 */
	public void setSegmentId(long segmentId);

	/**
	 * Returns the user ID of this segment_ user_ video.
	 *
	 * @return the user ID of this segment_ user_ video
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this segment_ user_ video.
	 *
	 * @param userId the user ID of this segment_ user_ video
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this segment_ user_ video.
	 *
	 * @return the user uuid of this segment_ user_ video
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this segment_ user_ video.
	 *
	 * @param userUuid the user uuid of this segment_ user_ video
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the video ID of this segment_ user_ video.
	 *
	 * @return the video ID of this segment_ user_ video
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this segment_ user_ video.
	 *
	 * @param videoId the video ID of this segment_ user_ video
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the segment user video ID of this segment_ user_ video.
	 *
	 * @return the segment user video ID of this segment_ user_ video
	 */
	public long getSegmentUserVideoId();

	/**
	 * Sets the segment user video ID of this segment_ user_ video.
	 *
	 * @param segmentUserVideoId the segment user video ID of this segment_ user_ video
	 */
	public void setSegmentUserVideoId(long segmentUserVideoId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Segment_User_Video segment_User_Video);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Segment_User_Video> toCacheModel();

	@Override
	public Segment_User_Video toEscapedModel();

	@Override
	public Segment_User_Video toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}