/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Segment service. Represents a row in the &quot;LG_Segment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.SegmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.SegmentImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Segment
 * @see de.uhh.l2g.plugins.model.impl.SegmentImpl
 * @see de.uhh.l2g.plugins.model.impl.SegmentModelImpl
 * @generated
 */
public interface SegmentModel extends BaseModel<Segment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a segment model instance should use the {@link Segment} interface instead.
	 */

	/**
	 * Returns the primary key of this segment.
	 *
	 * @return the primary key of this segment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this segment.
	 *
	 * @param primaryKey the primary key of this segment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the segment ID of this segment.
	 *
	 * @return the segment ID of this segment
	 */
	public long getSegmentId();

	/**
	 * Sets the segment ID of this segment.
	 *
	 * @param segmentId the segment ID of this segment
	 */
	public void setSegmentId(long segmentId);

	/**
	 * Returns the video ID of this segment.
	 *
	 * @return the video ID of this segment
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this segment.
	 *
	 * @param videoId the video ID of this segment
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the start of this segment.
	 *
	 * @return the start of this segment
	 */
	@AutoEscape
	public String getStart();

	/**
	 * Sets the start of this segment.
	 *
	 * @param start the start of this segment
	 */
	public void setStart(String start);

	/**
	 * Returns the title of this segment.
	 *
	 * @return the title of this segment
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this segment.
	 *
	 * @param title the title of this segment
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this segment.
	 *
	 * @return the description of this segment
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this segment.
	 *
	 * @param description the description of this segment
	 */
	public void setDescription(String description);

	/**
	 * Returns the end of this segment.
	 *
	 * @return the end of this segment
	 */
	@AutoEscape
	public String getEnd();

	/**
	 * Sets the end of this segment.
	 *
	 * @param end the end of this segment
	 */
	public void setEnd(String end);

	/**
	 * Returns the chapter of this segment.
	 *
	 * @return the chapter of this segment
	 */
	public int getChapter();

	/**
	 * Sets the chapter of this segment.
	 *
	 * @param chapter the chapter of this segment
	 */
	public void setChapter(int chapter);

	/**
	 * Returns the user ID of this segment.
	 *
	 * @return the user ID of this segment
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this segment.
	 *
	 * @param userId the user ID of this segment
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this segment.
	 *
	 * @return the user uuid of this segment
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this segment.
	 *
	 * @param userUuid the user uuid of this segment
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.uhh.l2g.plugins.model.Segment segment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.model.Segment> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.model.Segment toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.model.Segment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}