/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Tags service. Represents a row in the &quot;LG_Tags&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.TagsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.TagsImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Tags
 * @see de.uhh.l2g.plugins.model.impl.TagsImpl
 * @see de.uhh.l2g.plugins.model.impl.TagsModelImpl
 * @generated
 */
public interface TagsModel extends BaseModel<Tags> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tags model instance should use the {@link Tags} interface instead.
	 */

	/**
	 * Returns the primary key of this tags.
	 *
	 * @return the primary key of this tags
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tags.
	 *
	 * @param primaryKey the primary key of this tags
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tag ID of this tags.
	 *
	 * @return the tag ID of this tags
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this tags.
	 *
	 * @param tagId the tag ID of this tags
	 */
	public void setTagId(long tagId);

	/**
	 * Returns the is video of this tags.
	 *
	 * @return the is video of this tags
	 */
	public int getIsVideo();

	/**
	 * Sets the is video of this tags.
	 *
	 * @param isVideo the is video of this tags
	 */
	public void setIsVideo(int isVideo);

	/**
	 * Returns the is lectureseries of this tags.
	 *
	 * @return the is lectureseries of this tags
	 */
	public int getIsLectureseries();

	/**
	 * Sets the is lectureseries of this tags.
	 *
	 * @param isLectureseries the is lectureseries of this tags
	 */
	public void setIsLectureseries(int isLectureseries);

	/**
	 * Returns the tags of this tags.
	 *
	 * @return the tags of this tags
	 */
	@AutoEscape
	public String getTags();

	/**
	 * Sets the tags of this tags.
	 *
	 * @param tags the tags of this tags
	 */
	public void setTags(String tags);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Tags tags);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Tags> toCacheModel();

	@Override
	public Tags toEscapedModel();

	@Override
	public Tags toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}