/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Video_Institution service. Represents a row in the &quot;LG_Video_Institution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.Video_InstitutionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.Video_InstitutionImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_Institution
 * @see de.uhh.l2g.plugins.model.impl.Video_InstitutionImpl
 * @see de.uhh.l2g.plugins.model.impl.Video_InstitutionModelImpl
 * @generated
 */
public interface Video_InstitutionModel extends BaseModel<Video_Institution> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video_ institution model instance should use the {@link Video_Institution} interface instead.
	 */

	/**
	 * Returns the primary key of this video_ institution.
	 *
	 * @return the primary key of this video_ institution
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video_ institution.
	 *
	 * @param primaryKey the primary key of this video_ institution
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video institution ID of this video_ institution.
	 *
	 * @return the video institution ID of this video_ institution
	 */
	public long getVideoInstitutionId();

	/**
	 * Sets the video institution ID of this video_ institution.
	 *
	 * @param videoInstitutionId the video institution ID of this video_ institution
	 */
	public void setVideoInstitutionId(long videoInstitutionId);

	/**
	 * Returns the video ID of this video_ institution.
	 *
	 * @return the video ID of this video_ institution
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this video_ institution.
	 *
	 * @param videoId the video ID of this video_ institution
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the institution ID of this video_ institution.
	 *
	 * @return the institution ID of this video_ institution
	 */
	public long getInstitutionId();

	/**
	 * Sets the institution ID of this video_ institution.
	 *
	 * @param institutionId the institution ID of this video_ institution
	 */
	public void setInstitutionId(long institutionId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Video_Institution video_Institution);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Video_Institution> toCacheModel();

	@Override
	public Video_Institution toEscapedModel();

	@Override
	public Video_Institution toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}