/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Video_Creator service. Represents a row in the &quot;LG_Video_Creator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.Video_CreatorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.Video_CreatorImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_Creator
 * @see de.uhh.l2g.plugins.model.impl.Video_CreatorImpl
 * @see de.uhh.l2g.plugins.model.impl.Video_CreatorModelImpl
 * @generated
 */
public interface Video_CreatorModel extends BaseModel<Video_Creator> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video_ creator model instance should use the {@link Video_Creator} interface instead.
	 */

	/**
	 * Returns the primary key of this video_ creator.
	 *
	 * @return the primary key of this video_ creator
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video_ creator.
	 *
	 * @param primaryKey the primary key of this video_ creator
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video creator ID of this video_ creator.
	 *
	 * @return the video creator ID of this video_ creator
	 */
	public long getVideoCreatorId();

	/**
	 * Sets the video creator ID of this video_ creator.
	 *
	 * @param videoCreatorId the video creator ID of this video_ creator
	 */
	public void setVideoCreatorId(long videoCreatorId);

	/**
	 * Returns the creator ID of this video_ creator.
	 *
	 * @return the creator ID of this video_ creator
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this video_ creator.
	 *
	 * @param creatorId the creator ID of this video_ creator
	 */
	public void setCreatorId(long creatorId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Video_Creator video_Creator);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Video_Creator> toCacheModel();

	@Override
	public Video_Creator toEscapedModel();

	@Override
	public Video_Creator toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}