/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Video_Lectureseries service. Represents a row in the &quot;LG_Video_Lectureseries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.Video_LectureseriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.Video_LectureseriesImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Video_Lectureseries
 * @see de.uhh.l2g.plugins.model.impl.Video_LectureseriesImpl
 * @see de.uhh.l2g.plugins.model.impl.Video_LectureseriesModelImpl
 * @generated
 */
public interface Video_LectureseriesModel extends BaseModel<Video_Lectureseries> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video_ lectureseries model instance should use the {@link Video_Lectureseries} interface instead.
	 */

	/**
	 * Returns the primary key of this video_ lectureseries.
	 *
	 * @return the primary key of this video_ lectureseries
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video_ lectureseries.
	 *
	 * @param primaryKey the primary key of this video_ lectureseries
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video lectureseries ID of this video_ lectureseries.
	 *
	 * @return the video lectureseries ID of this video_ lectureseries
	 */
	public long getVideoLectureseriesId();

	/**
	 * Sets the video lectureseries ID of this video_ lectureseries.
	 *
	 * @param videoLectureseriesId the video lectureseries ID of this video_ lectureseries
	 */
	public void setVideoLectureseriesId(long videoLectureseriesId);

	/**
	 * Returns the video ID of this video_ lectureseries.
	 *
	 * @return the video ID of this video_ lectureseries
	 */
	public long getVideoId();

	/**
	 * Sets the video ID of this video_ lectureseries.
	 *
	 * @param videoId the video ID of this video_ lectureseries
	 */
	public void setVideoId(long videoId);

	/**
	 * Returns the lectureseries ID of this video_ lectureseries.
	 *
	 * @return the lectureseries ID of this video_ lectureseries
	 */
	public long getLectureseriesId();

	/**
	 * Sets the lectureseries ID of this video_ lectureseries.
	 *
	 * @param lectureseriesId the lectureseries ID of this video_ lectureseries
	 */
	public void setLectureseriesId(long lectureseriesId);

	/**
	 * Returns the open access of this video_ lectureseries.
	 *
	 * @return the open access of this video_ lectureseries
	 */
	public int getOpenAccess();

	/**
	 * Sets the open access of this video_ lectureseries.
	 *
	 * @param openAccess the open access of this video_ lectureseries
	 */
	public void setOpenAccess(int openAccess);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Video_Lectureseries video_Lectureseries);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Video_Lectureseries> toCacheModel();

	@Override
	public Video_Lectureseries toEscapedModel();

	@Override
	public Video_Lectureseries toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}