/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VideoStatistic service. Represents a row in the &quot;LG_VideoStatistic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.VideoStatisticModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.VideoStatisticImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see VideoStatistic
 * @see de.uhh.l2g.plugins.model.impl.VideoStatisticImpl
 * @see de.uhh.l2g.plugins.model.impl.VideoStatisticModelImpl
 * @generated
 */
public interface VideoStatisticModel extends BaseModel<VideoStatistic> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video statistic model instance should use the {@link VideoStatistic} interface instead.
	 */

	/**
	 * Returns the primary key of this video statistic.
	 *
	 * @return the primary key of this video statistic
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video statistic.
	 *
	 * @param primaryKey the primary key of this video statistic
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the video statistic ID of this video statistic.
	 *
	 * @return the video statistic ID of this video statistic
	 */
	public long getVideoStatisticId();

	/**
	 * Sets the video statistic ID of this video statistic.
	 *
	 * @param videoStatisticId the video statistic ID of this video statistic
	 */
	public void setVideoStatisticId(long videoStatisticId);

	/**
	 * Returns the group ID of this video statistic.
	 *
	 * @return the group ID of this video statistic
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this video statistic.
	 *
	 * @param groupId the group ID of this video statistic
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this video statistic.
	 *
	 * @return the company ID of this video statistic
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this video statistic.
	 *
	 * @param companyId the company ID of this video statistic
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this video statistic.
	 *
	 * @return the create date of this video statistic
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this video statistic.
	 *
	 * @param createDate the create date of this video statistic
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this video statistic.
	 *
	 * @return the modified date of this video statistic
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this video statistic.
	 *
	 * @param modifiedDate the modified date of this video statistic
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the compare date of this video statistic.
	 *
	 * @return the compare date of this video statistic
	 */
	public Date getCompareDate();

	/**
	 * Sets the compare date of this video statistic.
	 *
	 * @param compareDate the compare date of this video statistic
	 */
	public void setCompareDate(Date compareDate);

	/**
	 * Returns the total videos of this video statistic.
	 *
	 * @return the total videos of this video statistic
	 */
	public long getTotalVideos();

	/**
	 * Sets the total videos of this video statistic.
	 *
	 * @param totalVideos the total videos of this video statistic
	 */
	public void setTotalVideos(long totalVideos);

	/**
	 * Returns the public videos of this video statistic.
	 *
	 * @return the public videos of this video statistic
	 */
	public long getPublicVideos();

	/**
	 * Sets the public videos of this video statistic.
	 *
	 * @param publicVideos the public videos of this video statistic
	 */
	public void setPublicVideos(long publicVideos);

	/**
	 * Returns the private videos of this video statistic.
	 *
	 * @return the private videos of this video statistic
	 */
	public long getPrivateVideos();

	/**
	 * Sets the private videos of this video statistic.
	 *
	 * @param privateVideos the private videos of this video statistic
	 */
	public void setPrivateVideos(long privateVideos);

	/**
	 * Returns the current total of this video statistic.
	 *
	 * @return the current total of this video statistic
	 */
	public long getCurrentTotal();

	/**
	 * Sets the current total of this video statistic.
	 *
	 * @param currentTotal the current total of this video statistic
	 */
	public void setCurrentTotal(long currentTotal);

	/**
	 * Returns the current public of this video statistic.
	 *
	 * @return the current public of this video statistic
	 */
	public long getCurrentPublic();

	/**
	 * Sets the current public of this video statistic.
	 *
	 * @param currentPublic the current public of this video statistic
	 */
	public void setCurrentPublic(long currentPublic);

	/**
	 * Returns the current private of this video statistic.
	 *
	 * @return the current private of this video statistic
	 */
	public long getCurrentPrivate();

	/**
	 * Sets the current private of this video statistic.
	 *
	 * @param currentPrivate the current private of this video statistic
	 */
	public void setCurrentPrivate(long currentPrivate);

	/**
	 * Returns the pub percent of this video statistic.
	 *
	 * @return the pub percent of this video statistic
	 */
	public int getPubPercent();

	/**
	 * Sets the pub percent of this video statistic.
	 *
	 * @param pubPercent the pub percent of this video statistic
	 */
	public void setPubPercent(int pubPercent);

	/**
	 * Returns the priv percent of this video statistic.
	 *
	 * @return the priv percent of this video statistic
	 */
	public int getPrivPercent();

	/**
	 * Sets the priv percent of this video statistic.
	 *
	 * @param privPercent the priv percent of this video statistic
	 */
	public void setPrivPercent(int privPercent);

	/**
	 * Returns the current pub percent of this video statistic.
	 *
	 * @return the current pub percent of this video statistic
	 */
	public int getCurrentPubPercent();

	/**
	 * Sets the current pub percent of this video statistic.
	 *
	 * @param currentPubPercent the current pub percent of this video statistic
	 */
	public void setCurrentPubPercent(int currentPubPercent);

	/**
	 * Returns the current priv percent of this video statistic.
	 *
	 * @return the current priv percent of this video statistic
	 */
	public int getCurrentPrivPercent();

	/**
	 * Sets the current priv percent of this video statistic.
	 *
	 * @param currentPrivPercent the current priv percent of this video statistic
	 */
	public void setCurrentPrivPercent(int currentPrivPercent);

	/**
	 * Returns the interval name of this video statistic.
	 *
	 * @return the interval name of this video statistic
	 */
	@AutoEscape
	public String getIntervalName();

	/**
	 * Sets the interval name of this video statistic.
	 *
	 * @param intervalName the interval name of this video statistic
	 */
	public void setIntervalName(String intervalName);

	/**
	 * Returns the public diff of this video statistic.
	 *
	 * @return the public diff of this video statistic
	 */
	public int getPublicDiff();

	/**
	 * Sets the public diff of this video statistic.
	 *
	 * @param publicDiff the public diff of this video statistic
	 */
	public void setPublicDiff(int publicDiff);

	/**
	 * Returns the private diff of this video statistic.
	 *
	 * @return the private diff of this video statistic
	 */
	public int getPrivateDiff();

	/**
	 * Sets the private diff of this video statistic.
	 *
	 * @param privateDiff the private diff of this video statistic
	 */
	public void setPrivateDiff(int privateDiff);

	/**
	 * Returns the total diff of this video statistic.
	 *
	 * @return the total diff of this video statistic
	 */
	public int getTotalDiff();

	/**
	 * Sets the total diff of this video statistic.
	 *
	 * @param totalDiff the total diff of this video statistic
	 */
	public void setTotalDiff(int totalDiff);

	/**
	 * Returns the date diff of this video statistic.
	 *
	 * @return the date diff of this video statistic
	 */
	public int getDateDiff();

	/**
	 * Sets the date diff of this video statistic.
	 *
	 * @param dateDiff the date diff of this video statistic
	 */
	public void setDateDiff(int dateDiff);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.uhh.l2g.plugins.model.VideoStatistic videoStatistic);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.uhh.l2g.plugins.model.VideoStatistic> toCacheModel();

	@Override
	public de.uhh.l2g.plugins.model.VideoStatistic toEscapedModel();

	@Override
	public de.uhh.l2g.plugins.model.VideoStatistic toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}