/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Year service. Represents a row in the &quot;LG_Year&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.uhh.l2g.plugins.model.impl.YearModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.uhh.l2g.plugins.model.impl.YearImpl}.
 * </p>
 *
 * @author Iavor Sturm
 * @see Year
 * @see de.uhh.l2g.plugins.model.impl.YearImpl
 * @see de.uhh.l2g.plugins.model.impl.YearModelImpl
 * @generated
 */
public interface YearModel extends BaseModel<Year> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a year model instance should use the {@link Year} interface instead.
	 */

	/**
	 * Returns the primary key of this year.
	 *
	 * @return the primary key of this year
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this year.
	 *
	 * @param primaryKey the primary key of this year
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the year ID of this year.
	 *
	 * @return the year ID of this year
	 */
	public long getYearId();

	/**
	 * Sets the year ID of this year.
	 *
	 * @param yearId the year ID of this year
	 */
	public void setYearId(long yearId);

	/**
	 * Returns the parent ID of this year.
	 *
	 * @return the parent ID of this year
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this year.
	 *
	 * @param parentId the parent ID of this year
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the language ID of this year.
	 *
	 * @return the language ID of this year
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this year.
	 *
	 * @param languageId the language ID of this year
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the prefix of this year.
	 *
	 * @return the prefix of this year
	 */
	@AutoEscape
	public String getPrefix();

	/**
	 * Sets the prefix of this year.
	 *
	 * @param prefix the prefix of this year
	 */
	public void setPrefix(String prefix);

	/**
	 * Returns the name of this year.
	 *
	 * @return the name of this year
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this year.
	 *
	 * @param name the name of this year
	 */
	public void setName(String name);

	/**
	 * Returns the translation of this year.
	 *
	 * @return the translation of this year
	 */
	@AutoEscape
	public String getTranslation();

	/**
	 * Sets the translation of this year.
	 *
	 * @param translation the translation of this year
	 */
	public void setTranslation(String translation);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Year year);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Year> toCacheModel();

	@Override
	public Year toEscapedModel();

	@Override
	public Year toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}