/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.uhh.l2g.plugins.migration.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import de.uhh.l2g.plugins.migration.model.LegacyLastVideoList;
import de.uhh.l2g.plugins.migration.service.LegacyLastVideoListLocalService;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyAddressPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyContactPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyCoordinatorPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyFacilityHostPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyFacilityPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyHostPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyL2gSysPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyLastVideoListPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyLectureSeriesFacilityPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyLectureSeriesPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyLicensePersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyMetadataPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyOfficePersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyProducerLectureseriesPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyProducerPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacySegmentPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyStatisticsPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyUserPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyVideoFacilityPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyVideoHitlistPersistence;
import de.uhh.l2g.plugins.migration.service.persistence.LegacyVideoPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the legacy last video list local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link de.uhh.l2g.plugins.migration.service.impl.LegacyLastVideoListLocalServiceImpl}.
 * </p>
 *
 * @author unihh
 * @see de.uhh.l2g.plugins.migration.service.impl.LegacyLastVideoListLocalServiceImpl
 * @see de.uhh.l2g.plugins.migration.service.LegacyLastVideoListLocalServiceUtil
 * @generated
 */
public abstract class LegacyLastVideoListLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements LegacyLastVideoListLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link de.uhh.l2g.plugins.migration.service.LegacyLastVideoListLocalServiceUtil} to access the legacy last video list local service.
	 */

	/**
	 * Adds the legacy last video list to the database. Also notifies the appropriate model listeners.
	 *
	 * @param legacyLastVideoList the legacy last video list
	 * @return the legacy last video list that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LegacyLastVideoList addLegacyLastVideoList(
		LegacyLastVideoList legacyLastVideoList) throws SystemException {
		legacyLastVideoList.setNew(true);

		return legacyLastVideoListPersistence.update(legacyLastVideoList);
	}

	/**
	 * Creates a new legacy last video list with the primary key. Does not add the legacy last video list to the database.
	 *
	 * @param id the primary key for the new legacy last video list
	 * @return the new legacy last video list
	 */
	@Override
	public LegacyLastVideoList createLegacyLastVideoList(int id) {
		return legacyLastVideoListPersistence.create(id);
	}

	/**
	 * Deletes the legacy last video list with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the legacy last video list
	 * @return the legacy last video list that was removed
	 * @throws PortalException if a legacy last video list with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LegacyLastVideoList deleteLegacyLastVideoList(int id)
		throws PortalException, SystemException {
		return legacyLastVideoListPersistence.remove(id);
	}

	/**
	 * Deletes the legacy last video list from the database. Also notifies the appropriate model listeners.
	 *
	 * @param legacyLastVideoList the legacy last video list
	 * @return the legacy last video list that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LegacyLastVideoList deleteLegacyLastVideoList(
		LegacyLastVideoList legacyLastVideoList) throws SystemException {
		return legacyLastVideoListPersistence.remove(legacyLastVideoList);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(LegacyLastVideoList.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return legacyLastVideoListPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link de.uhh.l2g.plugins.migration.model.impl.LegacyLastVideoListModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return legacyLastVideoListPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link de.uhh.l2g.plugins.migration.model.impl.LegacyLastVideoListModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return legacyLastVideoListPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return legacyLastVideoListPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return legacyLastVideoListPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public LegacyLastVideoList fetchLegacyLastVideoList(int id)
		throws SystemException {
		return legacyLastVideoListPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the legacy last video list with the primary key.
	 *
	 * @param id the primary key of the legacy last video list
	 * @return the legacy last video list
	 * @throws PortalException if a legacy last video list with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public LegacyLastVideoList getLegacyLastVideoList(int id)
		throws PortalException, SystemException {
		return legacyLastVideoListPersistence.findByPrimaryKey(id);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return legacyLastVideoListPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the legacy last video lists.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link de.uhh.l2g.plugins.migration.model.impl.LegacyLastVideoListModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of legacy last video lists
	 * @param end the upper bound of the range of legacy last video lists (not inclusive)
	 * @return the range of legacy last video lists
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<LegacyLastVideoList> getLegacyLastVideoLists(int start, int end)
		throws SystemException {
		return legacyLastVideoListPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of legacy last video lists.
	 *
	 * @return the number of legacy last video lists
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getLegacyLastVideoListsCount() throws SystemException {
		return legacyLastVideoListPersistence.countAll();
	}

	/**
	 * Updates the legacy last video list in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param legacyLastVideoList the legacy last video list
	 * @return the legacy last video list that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LegacyLastVideoList updateLegacyLastVideoList(
		LegacyLastVideoList legacyLastVideoList) throws SystemException {
		return legacyLastVideoListPersistence.update(legacyLastVideoList);
	}

	/**
	 * Returns the legacy address local service.
	 *
	 * @return the legacy address local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyAddressLocalService getLegacyAddressLocalService() {
		return legacyAddressLocalService;
	}

	/**
	 * Sets the legacy address local service.
	 *
	 * @param legacyAddressLocalService the legacy address local service
	 */
	public void setLegacyAddressLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyAddressLocalService legacyAddressLocalService) {
		this.legacyAddressLocalService = legacyAddressLocalService;
	}

	/**
	 * Returns the legacy address persistence.
	 *
	 * @return the legacy address persistence
	 */
	public LegacyAddressPersistence getLegacyAddressPersistence() {
		return legacyAddressPersistence;
	}

	/**
	 * Sets the legacy address persistence.
	 *
	 * @param legacyAddressPersistence the legacy address persistence
	 */
	public void setLegacyAddressPersistence(
		LegacyAddressPersistence legacyAddressPersistence) {
		this.legacyAddressPersistence = legacyAddressPersistence;
	}

	/**
	 * Returns the legacy contact local service.
	 *
	 * @return the legacy contact local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyContactLocalService getLegacyContactLocalService() {
		return legacyContactLocalService;
	}

	/**
	 * Sets the legacy contact local service.
	 *
	 * @param legacyContactLocalService the legacy contact local service
	 */
	public void setLegacyContactLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyContactLocalService legacyContactLocalService) {
		this.legacyContactLocalService = legacyContactLocalService;
	}

	/**
	 * Returns the legacy contact persistence.
	 *
	 * @return the legacy contact persistence
	 */
	public LegacyContactPersistence getLegacyContactPersistence() {
		return legacyContactPersistence;
	}

	/**
	 * Sets the legacy contact persistence.
	 *
	 * @param legacyContactPersistence the legacy contact persistence
	 */
	public void setLegacyContactPersistence(
		LegacyContactPersistence legacyContactPersistence) {
		this.legacyContactPersistence = legacyContactPersistence;
	}

	/**
	 * Returns the legacy coordinator local service.
	 *
	 * @return the legacy coordinator local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyCoordinatorLocalService getLegacyCoordinatorLocalService() {
		return legacyCoordinatorLocalService;
	}

	/**
	 * Sets the legacy coordinator local service.
	 *
	 * @param legacyCoordinatorLocalService the legacy coordinator local service
	 */
	public void setLegacyCoordinatorLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyCoordinatorLocalService legacyCoordinatorLocalService) {
		this.legacyCoordinatorLocalService = legacyCoordinatorLocalService;
	}

	/**
	 * Returns the legacy coordinator persistence.
	 *
	 * @return the legacy coordinator persistence
	 */
	public LegacyCoordinatorPersistence getLegacyCoordinatorPersistence() {
		return legacyCoordinatorPersistence;
	}

	/**
	 * Sets the legacy coordinator persistence.
	 *
	 * @param legacyCoordinatorPersistence the legacy coordinator persistence
	 */
	public void setLegacyCoordinatorPersistence(
		LegacyCoordinatorPersistence legacyCoordinatorPersistence) {
		this.legacyCoordinatorPersistence = legacyCoordinatorPersistence;
	}

	/**
	 * Returns the legacy facility local service.
	 *
	 * @return the legacy facility local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyFacilityLocalService getLegacyFacilityLocalService() {
		return legacyFacilityLocalService;
	}

	/**
	 * Sets the legacy facility local service.
	 *
	 * @param legacyFacilityLocalService the legacy facility local service
	 */
	public void setLegacyFacilityLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyFacilityLocalService legacyFacilityLocalService) {
		this.legacyFacilityLocalService = legacyFacilityLocalService;
	}

	/**
	 * Returns the legacy facility persistence.
	 *
	 * @return the legacy facility persistence
	 */
	public LegacyFacilityPersistence getLegacyFacilityPersistence() {
		return legacyFacilityPersistence;
	}

	/**
	 * Sets the legacy facility persistence.
	 *
	 * @param legacyFacilityPersistence the legacy facility persistence
	 */
	public void setLegacyFacilityPersistence(
		LegacyFacilityPersistence legacyFacilityPersistence) {
		this.legacyFacilityPersistence = legacyFacilityPersistence;
	}

	/**
	 * Returns the legacy facility host local service.
	 *
	 * @return the legacy facility host local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyFacilityHostLocalService getLegacyFacilityHostLocalService() {
		return legacyFacilityHostLocalService;
	}

	/**
	 * Sets the legacy facility host local service.
	 *
	 * @param legacyFacilityHostLocalService the legacy facility host local service
	 */
	public void setLegacyFacilityHostLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyFacilityHostLocalService legacyFacilityHostLocalService) {
		this.legacyFacilityHostLocalService = legacyFacilityHostLocalService;
	}

	/**
	 * Returns the legacy facility host persistence.
	 *
	 * @return the legacy facility host persistence
	 */
	public LegacyFacilityHostPersistence getLegacyFacilityHostPersistence() {
		return legacyFacilityHostPersistence;
	}

	/**
	 * Sets the legacy facility host persistence.
	 *
	 * @param legacyFacilityHostPersistence the legacy facility host persistence
	 */
	public void setLegacyFacilityHostPersistence(
		LegacyFacilityHostPersistence legacyFacilityHostPersistence) {
		this.legacyFacilityHostPersistence = legacyFacilityHostPersistence;
	}

	/**
	 * Returns the legacy host local service.
	 *
	 * @return the legacy host local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyHostLocalService getLegacyHostLocalService() {
		return legacyHostLocalService;
	}

	/**
	 * Sets the legacy host local service.
	 *
	 * @param legacyHostLocalService the legacy host local service
	 */
	public void setLegacyHostLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyHostLocalService legacyHostLocalService) {
		this.legacyHostLocalService = legacyHostLocalService;
	}

	/**
	 * Returns the legacy host persistence.
	 *
	 * @return the legacy host persistence
	 */
	public LegacyHostPersistence getLegacyHostPersistence() {
		return legacyHostPersistence;
	}

	/**
	 * Sets the legacy host persistence.
	 *
	 * @param legacyHostPersistence the legacy host persistence
	 */
	public void setLegacyHostPersistence(
		LegacyHostPersistence legacyHostPersistence) {
		this.legacyHostPersistence = legacyHostPersistence;
	}

	/**
	 * Returns the legacy l2g sys local service.
	 *
	 * @return the legacy l2g sys local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyL2gSysLocalService getLegacyL2gSysLocalService() {
		return legacyL2gSysLocalService;
	}

	/**
	 * Sets the legacy l2g sys local service.
	 *
	 * @param legacyL2gSysLocalService the legacy l2g sys local service
	 */
	public void setLegacyL2gSysLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyL2gSysLocalService legacyL2gSysLocalService) {
		this.legacyL2gSysLocalService = legacyL2gSysLocalService;
	}

	/**
	 * Returns the legacy l2g sys persistence.
	 *
	 * @return the legacy l2g sys persistence
	 */
	public LegacyL2gSysPersistence getLegacyL2gSysPersistence() {
		return legacyL2gSysPersistence;
	}

	/**
	 * Sets the legacy l2g sys persistence.
	 *
	 * @param legacyL2gSysPersistence the legacy l2g sys persistence
	 */
	public void setLegacyL2gSysPersistence(
		LegacyL2gSysPersistence legacyL2gSysPersistence) {
		this.legacyL2gSysPersistence = legacyL2gSysPersistence;
	}

	/**
	 * Returns the legacy last video list local service.
	 *
	 * @return the legacy last video list local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyLastVideoListLocalService getLegacyLastVideoListLocalService() {
		return legacyLastVideoListLocalService;
	}

	/**
	 * Sets the legacy last video list local service.
	 *
	 * @param legacyLastVideoListLocalService the legacy last video list local service
	 */
	public void setLegacyLastVideoListLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyLastVideoListLocalService legacyLastVideoListLocalService) {
		this.legacyLastVideoListLocalService = legacyLastVideoListLocalService;
	}

	/**
	 * Returns the legacy last video list persistence.
	 *
	 * @return the legacy last video list persistence
	 */
	public LegacyLastVideoListPersistence getLegacyLastVideoListPersistence() {
		return legacyLastVideoListPersistence;
	}

	/**
	 * Sets the legacy last video list persistence.
	 *
	 * @param legacyLastVideoListPersistence the legacy last video list persistence
	 */
	public void setLegacyLastVideoListPersistence(
		LegacyLastVideoListPersistence legacyLastVideoListPersistence) {
		this.legacyLastVideoListPersistence = legacyLastVideoListPersistence;
	}

	/**
	 * Returns the legacy lecture series local service.
	 *
	 * @return the legacy lecture series local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyLectureSeriesLocalService getLegacyLectureSeriesLocalService() {
		return legacyLectureSeriesLocalService;
	}

	/**
	 * Sets the legacy lecture series local service.
	 *
	 * @param legacyLectureSeriesLocalService the legacy lecture series local service
	 */
	public void setLegacyLectureSeriesLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyLectureSeriesLocalService legacyLectureSeriesLocalService) {
		this.legacyLectureSeriesLocalService = legacyLectureSeriesLocalService;
	}

	/**
	 * Returns the legacy lecture series persistence.
	 *
	 * @return the legacy lecture series persistence
	 */
	public LegacyLectureSeriesPersistence getLegacyLectureSeriesPersistence() {
		return legacyLectureSeriesPersistence;
	}

	/**
	 * Sets the legacy lecture series persistence.
	 *
	 * @param legacyLectureSeriesPersistence the legacy lecture series persistence
	 */
	public void setLegacyLectureSeriesPersistence(
		LegacyLectureSeriesPersistence legacyLectureSeriesPersistence) {
		this.legacyLectureSeriesPersistence = legacyLectureSeriesPersistence;
	}

	/**
	 * Returns the legacy lecture series facility local service.
	 *
	 * @return the legacy lecture series facility local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyLectureSeriesFacilityLocalService getLegacyLectureSeriesFacilityLocalService() {
		return legacyLectureSeriesFacilityLocalService;
	}

	/**
	 * Sets the legacy lecture series facility local service.
	 *
	 * @param legacyLectureSeriesFacilityLocalService the legacy lecture series facility local service
	 */
	public void setLegacyLectureSeriesFacilityLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyLectureSeriesFacilityLocalService legacyLectureSeriesFacilityLocalService) {
		this.legacyLectureSeriesFacilityLocalService = legacyLectureSeriesFacilityLocalService;
	}

	/**
	 * Returns the legacy lecture series facility persistence.
	 *
	 * @return the legacy lecture series facility persistence
	 */
	public LegacyLectureSeriesFacilityPersistence getLegacyLectureSeriesFacilityPersistence() {
		return legacyLectureSeriesFacilityPersistence;
	}

	/**
	 * Sets the legacy lecture series facility persistence.
	 *
	 * @param legacyLectureSeriesFacilityPersistence the legacy lecture series facility persistence
	 */
	public void setLegacyLectureSeriesFacilityPersistence(
		LegacyLectureSeriesFacilityPersistence legacyLectureSeriesFacilityPersistence) {
		this.legacyLectureSeriesFacilityPersistence = legacyLectureSeriesFacilityPersistence;
	}

	/**
	 * Returns the legacy license local service.
	 *
	 * @return the legacy license local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyLicenseLocalService getLegacyLicenseLocalService() {
		return legacyLicenseLocalService;
	}

	/**
	 * Sets the legacy license local service.
	 *
	 * @param legacyLicenseLocalService the legacy license local service
	 */
	public void setLegacyLicenseLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyLicenseLocalService legacyLicenseLocalService) {
		this.legacyLicenseLocalService = legacyLicenseLocalService;
	}

	/**
	 * Returns the legacy license persistence.
	 *
	 * @return the legacy license persistence
	 */
	public LegacyLicensePersistence getLegacyLicensePersistence() {
		return legacyLicensePersistence;
	}

	/**
	 * Sets the legacy license persistence.
	 *
	 * @param legacyLicensePersistence the legacy license persistence
	 */
	public void setLegacyLicensePersistence(
		LegacyLicensePersistence legacyLicensePersistence) {
		this.legacyLicensePersistence = legacyLicensePersistence;
	}

	/**
	 * Returns the legacy metadata local service.
	 *
	 * @return the legacy metadata local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyMetadataLocalService getLegacyMetadataLocalService() {
		return legacyMetadataLocalService;
	}

	/**
	 * Sets the legacy metadata local service.
	 *
	 * @param legacyMetadataLocalService the legacy metadata local service
	 */
	public void setLegacyMetadataLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyMetadataLocalService legacyMetadataLocalService) {
		this.legacyMetadataLocalService = legacyMetadataLocalService;
	}

	/**
	 * Returns the legacy metadata persistence.
	 *
	 * @return the legacy metadata persistence
	 */
	public LegacyMetadataPersistence getLegacyMetadataPersistence() {
		return legacyMetadataPersistence;
	}

	/**
	 * Sets the legacy metadata persistence.
	 *
	 * @param legacyMetadataPersistence the legacy metadata persistence
	 */
	public void setLegacyMetadataPersistence(
		LegacyMetadataPersistence legacyMetadataPersistence) {
		this.legacyMetadataPersistence = legacyMetadataPersistence;
	}

	/**
	 * Returns the legacy office local service.
	 *
	 * @return the legacy office local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyOfficeLocalService getLegacyOfficeLocalService() {
		return legacyOfficeLocalService;
	}

	/**
	 * Sets the legacy office local service.
	 *
	 * @param legacyOfficeLocalService the legacy office local service
	 */
	public void setLegacyOfficeLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyOfficeLocalService legacyOfficeLocalService) {
		this.legacyOfficeLocalService = legacyOfficeLocalService;
	}

	/**
	 * Returns the legacy office persistence.
	 *
	 * @return the legacy office persistence
	 */
	public LegacyOfficePersistence getLegacyOfficePersistence() {
		return legacyOfficePersistence;
	}

	/**
	 * Sets the legacy office persistence.
	 *
	 * @param legacyOfficePersistence the legacy office persistence
	 */
	public void setLegacyOfficePersistence(
		LegacyOfficePersistence legacyOfficePersistence) {
		this.legacyOfficePersistence = legacyOfficePersistence;
	}

	/**
	 * Returns the legacy producer local service.
	 *
	 * @return the legacy producer local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyProducerLocalService getLegacyProducerLocalService() {
		return legacyProducerLocalService;
	}

	/**
	 * Sets the legacy producer local service.
	 *
	 * @param legacyProducerLocalService the legacy producer local service
	 */
	public void setLegacyProducerLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyProducerLocalService legacyProducerLocalService) {
		this.legacyProducerLocalService = legacyProducerLocalService;
	}

	/**
	 * Returns the legacy producer persistence.
	 *
	 * @return the legacy producer persistence
	 */
	public LegacyProducerPersistence getLegacyProducerPersistence() {
		return legacyProducerPersistence;
	}

	/**
	 * Sets the legacy producer persistence.
	 *
	 * @param legacyProducerPersistence the legacy producer persistence
	 */
	public void setLegacyProducerPersistence(
		LegacyProducerPersistence legacyProducerPersistence) {
		this.legacyProducerPersistence = legacyProducerPersistence;
	}

	/**
	 * Returns the legacy producer lectureseries local service.
	 *
	 * @return the legacy producer lectureseries local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyProducerLectureseriesLocalService getLegacyProducerLectureseriesLocalService() {
		return legacyProducerLectureseriesLocalService;
	}

	/**
	 * Sets the legacy producer lectureseries local service.
	 *
	 * @param legacyProducerLectureseriesLocalService the legacy producer lectureseries local service
	 */
	public void setLegacyProducerLectureseriesLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyProducerLectureseriesLocalService legacyProducerLectureseriesLocalService) {
		this.legacyProducerLectureseriesLocalService = legacyProducerLectureseriesLocalService;
	}

	/**
	 * Returns the legacy producer lectureseries persistence.
	 *
	 * @return the legacy producer lectureseries persistence
	 */
	public LegacyProducerLectureseriesPersistence getLegacyProducerLectureseriesPersistence() {
		return legacyProducerLectureseriesPersistence;
	}

	/**
	 * Sets the legacy producer lectureseries persistence.
	 *
	 * @param legacyProducerLectureseriesPersistence the legacy producer lectureseries persistence
	 */
	public void setLegacyProducerLectureseriesPersistence(
		LegacyProducerLectureseriesPersistence legacyProducerLectureseriesPersistence) {
		this.legacyProducerLectureseriesPersistence = legacyProducerLectureseriesPersistence;
	}

	/**
	 * Returns the legacy segment local service.
	 *
	 * @return the legacy segment local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacySegmentLocalService getLegacySegmentLocalService() {
		return legacySegmentLocalService;
	}

	/**
	 * Sets the legacy segment local service.
	 *
	 * @param legacySegmentLocalService the legacy segment local service
	 */
	public void setLegacySegmentLocalService(
		de.uhh.l2g.plugins.migration.service.LegacySegmentLocalService legacySegmentLocalService) {
		this.legacySegmentLocalService = legacySegmentLocalService;
	}

	/**
	 * Returns the legacy segment persistence.
	 *
	 * @return the legacy segment persistence
	 */
	public LegacySegmentPersistence getLegacySegmentPersistence() {
		return legacySegmentPersistence;
	}

	/**
	 * Sets the legacy segment persistence.
	 *
	 * @param legacySegmentPersistence the legacy segment persistence
	 */
	public void setLegacySegmentPersistence(
		LegacySegmentPersistence legacySegmentPersistence) {
		this.legacySegmentPersistence = legacySegmentPersistence;
	}

	/**
	 * Returns the legacy statistics local service.
	 *
	 * @return the legacy statistics local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyStatisticsLocalService getLegacyStatisticsLocalService() {
		return legacyStatisticsLocalService;
	}

	/**
	 * Sets the legacy statistics local service.
	 *
	 * @param legacyStatisticsLocalService the legacy statistics local service
	 */
	public void setLegacyStatisticsLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyStatisticsLocalService legacyStatisticsLocalService) {
		this.legacyStatisticsLocalService = legacyStatisticsLocalService;
	}

	/**
	 * Returns the legacy statistics persistence.
	 *
	 * @return the legacy statistics persistence
	 */
	public LegacyStatisticsPersistence getLegacyStatisticsPersistence() {
		return legacyStatisticsPersistence;
	}

	/**
	 * Sets the legacy statistics persistence.
	 *
	 * @param legacyStatisticsPersistence the legacy statistics persistence
	 */
	public void setLegacyStatisticsPersistence(
		LegacyStatisticsPersistence legacyStatisticsPersistence) {
		this.legacyStatisticsPersistence = legacyStatisticsPersistence;
	}

	/**
	 * Returns the legacy user local service.
	 *
	 * @return the legacy user local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyUserLocalService getLegacyUserLocalService() {
		return legacyUserLocalService;
	}

	/**
	 * Sets the legacy user local service.
	 *
	 * @param legacyUserLocalService the legacy user local service
	 */
	public void setLegacyUserLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyUserLocalService legacyUserLocalService) {
		this.legacyUserLocalService = legacyUserLocalService;
	}

	/**
	 * Returns the legacy user persistence.
	 *
	 * @return the legacy user persistence
	 */
	public LegacyUserPersistence getLegacyUserPersistence() {
		return legacyUserPersistence;
	}

	/**
	 * Sets the legacy user persistence.
	 *
	 * @param legacyUserPersistence the legacy user persistence
	 */
	public void setLegacyUserPersistence(
		LegacyUserPersistence legacyUserPersistence) {
		this.legacyUserPersistence = legacyUserPersistence;
	}

	/**
	 * Returns the legacy video local service.
	 *
	 * @return the legacy video local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyVideoLocalService getLegacyVideoLocalService() {
		return legacyVideoLocalService;
	}

	/**
	 * Sets the legacy video local service.
	 *
	 * @param legacyVideoLocalService the legacy video local service
	 */
	public void setLegacyVideoLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyVideoLocalService legacyVideoLocalService) {
		this.legacyVideoLocalService = legacyVideoLocalService;
	}

	/**
	 * Returns the legacy video persistence.
	 *
	 * @return the legacy video persistence
	 */
	public LegacyVideoPersistence getLegacyVideoPersistence() {
		return legacyVideoPersistence;
	}

	/**
	 * Sets the legacy video persistence.
	 *
	 * @param legacyVideoPersistence the legacy video persistence
	 */
	public void setLegacyVideoPersistence(
		LegacyVideoPersistence legacyVideoPersistence) {
		this.legacyVideoPersistence = legacyVideoPersistence;
	}

	/**
	 * Returns the legacy video facility local service.
	 *
	 * @return the legacy video facility local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyVideoFacilityLocalService getLegacyVideoFacilityLocalService() {
		return legacyVideoFacilityLocalService;
	}

	/**
	 * Sets the legacy video facility local service.
	 *
	 * @param legacyVideoFacilityLocalService the legacy video facility local service
	 */
	public void setLegacyVideoFacilityLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyVideoFacilityLocalService legacyVideoFacilityLocalService) {
		this.legacyVideoFacilityLocalService = legacyVideoFacilityLocalService;
	}

	/**
	 * Returns the legacy video facility persistence.
	 *
	 * @return the legacy video facility persistence
	 */
	public LegacyVideoFacilityPersistence getLegacyVideoFacilityPersistence() {
		return legacyVideoFacilityPersistence;
	}

	/**
	 * Sets the legacy video facility persistence.
	 *
	 * @param legacyVideoFacilityPersistence the legacy video facility persistence
	 */
	public void setLegacyVideoFacilityPersistence(
		LegacyVideoFacilityPersistence legacyVideoFacilityPersistence) {
		this.legacyVideoFacilityPersistence = legacyVideoFacilityPersistence;
	}

	/**
	 * Returns the legacy video hitlist local service.
	 *
	 * @return the legacy video hitlist local service
	 */
	public de.uhh.l2g.plugins.migration.service.LegacyVideoHitlistLocalService getLegacyVideoHitlistLocalService() {
		return legacyVideoHitlistLocalService;
	}

	/**
	 * Sets the legacy video hitlist local service.
	 *
	 * @param legacyVideoHitlistLocalService the legacy video hitlist local service
	 */
	public void setLegacyVideoHitlistLocalService(
		de.uhh.l2g.plugins.migration.service.LegacyVideoHitlistLocalService legacyVideoHitlistLocalService) {
		this.legacyVideoHitlistLocalService = legacyVideoHitlistLocalService;
	}

	/**
	 * Returns the legacy video hitlist persistence.
	 *
	 * @return the legacy video hitlist persistence
	 */
	public LegacyVideoHitlistPersistence getLegacyVideoHitlistPersistence() {
		return legacyVideoHitlistPersistence;
	}

	/**
	 * Sets the legacy video hitlist persistence.
	 *
	 * @param legacyVideoHitlistPersistence the legacy video hitlist persistence
	 */
	public void setLegacyVideoHitlistPersistence(
		LegacyVideoHitlistPersistence legacyVideoHitlistPersistence) {
		this.legacyVideoHitlistPersistence = legacyVideoHitlistPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("de.uhh.l2g.plugins.migration.model.LegacyLastVideoList",
			legacyLastVideoListLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"de.uhh.l2g.plugins.migration.model.LegacyLastVideoList");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return LegacyLastVideoList.class;
	}

	protected String getModelClassName() {
		return LegacyLastVideoList.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = legacyLastVideoListPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyAddressLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyAddressLocalService legacyAddressLocalService;
	@BeanReference(type = LegacyAddressPersistence.class)
	protected LegacyAddressPersistence legacyAddressPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyContactLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyContactLocalService legacyContactLocalService;
	@BeanReference(type = LegacyContactPersistence.class)
	protected LegacyContactPersistence legacyContactPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyCoordinatorLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyCoordinatorLocalService legacyCoordinatorLocalService;
	@BeanReference(type = LegacyCoordinatorPersistence.class)
	protected LegacyCoordinatorPersistence legacyCoordinatorPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyFacilityLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyFacilityLocalService legacyFacilityLocalService;
	@BeanReference(type = LegacyFacilityPersistence.class)
	protected LegacyFacilityPersistence legacyFacilityPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyFacilityHostLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyFacilityHostLocalService legacyFacilityHostLocalService;
	@BeanReference(type = LegacyFacilityHostPersistence.class)
	protected LegacyFacilityHostPersistence legacyFacilityHostPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyHostLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyHostLocalService legacyHostLocalService;
	@BeanReference(type = LegacyHostPersistence.class)
	protected LegacyHostPersistence legacyHostPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyL2gSysLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyL2gSysLocalService legacyL2gSysLocalService;
	@BeanReference(type = LegacyL2gSysPersistence.class)
	protected LegacyL2gSysPersistence legacyL2gSysPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyLastVideoListLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyLastVideoListLocalService legacyLastVideoListLocalService;
	@BeanReference(type = LegacyLastVideoListPersistence.class)
	protected LegacyLastVideoListPersistence legacyLastVideoListPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyLectureSeriesLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyLectureSeriesLocalService legacyLectureSeriesLocalService;
	@BeanReference(type = LegacyLectureSeriesPersistence.class)
	protected LegacyLectureSeriesPersistence legacyLectureSeriesPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyLectureSeriesFacilityLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyLectureSeriesFacilityLocalService legacyLectureSeriesFacilityLocalService;
	@BeanReference(type = LegacyLectureSeriesFacilityPersistence.class)
	protected LegacyLectureSeriesFacilityPersistence legacyLectureSeriesFacilityPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyLicenseLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyLicenseLocalService legacyLicenseLocalService;
	@BeanReference(type = LegacyLicensePersistence.class)
	protected LegacyLicensePersistence legacyLicensePersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyMetadataLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyMetadataLocalService legacyMetadataLocalService;
	@BeanReference(type = LegacyMetadataPersistence.class)
	protected LegacyMetadataPersistence legacyMetadataPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyOfficeLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyOfficeLocalService legacyOfficeLocalService;
	@BeanReference(type = LegacyOfficePersistence.class)
	protected LegacyOfficePersistence legacyOfficePersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyProducerLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyProducerLocalService legacyProducerLocalService;
	@BeanReference(type = LegacyProducerPersistence.class)
	protected LegacyProducerPersistence legacyProducerPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyProducerLectureseriesLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyProducerLectureseriesLocalService legacyProducerLectureseriesLocalService;
	@BeanReference(type = LegacyProducerLectureseriesPersistence.class)
	protected LegacyProducerLectureseriesPersistence legacyProducerLectureseriesPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacySegmentLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacySegmentLocalService legacySegmentLocalService;
	@BeanReference(type = LegacySegmentPersistence.class)
	protected LegacySegmentPersistence legacySegmentPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyStatisticsLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyStatisticsLocalService legacyStatisticsLocalService;
	@BeanReference(type = LegacyStatisticsPersistence.class)
	protected LegacyStatisticsPersistence legacyStatisticsPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyUserLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyUserLocalService legacyUserLocalService;
	@BeanReference(type = LegacyUserPersistence.class)
	protected LegacyUserPersistence legacyUserPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyVideoLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyVideoLocalService legacyVideoLocalService;
	@BeanReference(type = LegacyVideoPersistence.class)
	protected LegacyVideoPersistence legacyVideoPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyVideoFacilityLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyVideoFacilityLocalService legacyVideoFacilityLocalService;
	@BeanReference(type = LegacyVideoFacilityPersistence.class)
	protected LegacyVideoFacilityPersistence legacyVideoFacilityPersistence;
	@BeanReference(type = de.uhh.l2g.plugins.migration.service.LegacyVideoHitlistLocalService.class)
	protected de.uhh.l2g.plugins.migration.service.LegacyVideoHitlistLocalService legacyVideoHitlistLocalService;
	@BeanReference(type = LegacyVideoHitlistPersistence.class)
	protected LegacyVideoHitlistPersistence legacyVideoHitlistPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private LegacyLastVideoListLocalServiceClpInvoker _clpInvoker = new LegacyLastVideoListLocalServiceClpInvoker();
}